---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broadcaster
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: broadcaster
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: broadcaster
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: broadcaster
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
