---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broadcaster
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: broadcaster

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broadcaster
rules:
  - apiGroups:
      - discovery.liqo.io
    resources:
      - peeringrequests
    verbs:
      - get
      - update
      - delete
  - apiGroups:
      - config.liqo.io
    resources:
      - clusterconfigs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: broadcaster
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
    resourceNames:
      - vk-remote

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: broadcaster
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: broadcaster
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: broadcaster

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: broadcaster
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: broadcaster
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: broadcaster

---
# Remote VirtualKubelet
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vk-remote
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: broadcaster

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vk-remote
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: vk-remote
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
