---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: peering-request-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peering-request-operator
rules:
  - apiGroups:
      - discovery.liqo.io
    resources:
      - peeringrequests
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create
      - delete
  - apiGroups:
      - discovery.liqo.io
    resources:
      - foreignclusters
    verbs:
      - list
      - update
      - create
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - patch
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - patch
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: peering-request-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: peering-request-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: peering-request-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: peering-request-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: peering-request-operator
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: peering-request-operator
  template:
    metadata:
      labels:
        run: peering-request-operator
    spec:
      serviceAccountName: peering-request-operator
      containers:
        - image: {{ .Values.operator.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          name: peering-request-operator
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: 8443
          args:
            - "--broadcaster-image"
            - {{ .Values.broadcaster.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{ if .Values.global.apiServer.ip }}
            - name: APISERVER
              value: "{{ .Values.global.apiServer.ip }}"
            {{ end }}
            {{ if .Values.global.apiServer.port }}
            - name: APISERVER_PORT
              value: "{{ .Values.global.apiServer.port }}"
            {{ end }}
            {{ if .Values.global.authServer.ip }}
            - name: AUTH_ADDR
              value: "{{ .Values.global.authServer.ip }}"
            {{ end }}
            {{ if .Values.global.authServer.port }}
            - name: AUTH_SVC_PORT
              value: "{{ .Values.global.authServer.port }}"
          {{ end }}
          resources:
            limits:
              cpu: 100m
              memory: 50M
            requests:
              cpu: 100m
              memory: 50M