---
{{- $advertisementConfig := (merge (dict "name" .Values.componentNames.advertisement "module" .Values.moduleNames.sharing) .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $advertisementConfig }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "liqo.labels" $advertisementConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $advertisementConfig }}
  labels:
    {{- include "liqo.labels" $advertisementConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $advertisementConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---