---
{{- $advertisementConfig := (merge (dict "name" .Values.componentNames.advertisement "module" .Values.moduleNames.sharing) .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "liqo.labels" $advertisementConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $advertisementConfig }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $advertisementConfig | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "liqo.selectorLabels" $advertisementConfig | nindent 8 }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $advertisementConfig }}
      containers:
      - image: {{ .Values.advController.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: advertisement-operator
        command: ["/usr/bin/advertisement-operator"]
        args:
          - "--cluster-id"
          - "$(CLUSTER_ID)"
          - "--kubelet-namespace"
          - "$(POD_NAMESPACE)"
          - "--kubelet-image"
          - {{ .Values.virtualKubelet.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
          - "--init-kubelet-image"
          - {{ .Values.initVk.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: cluster-id
                key: cluster-id
          - name: POD_NAMESPACE
            valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M