---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    run: advertisement-operator
    app: liqo.io
  name: advertisement-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: advertisement-operator
  template:
    metadata:
      labels:
        run: advertisement-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      serviceAccountName: advertisement-operator
      containers:
      - image: {{ .Values.advController.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: advertisement-operator
        command: ["/usr/bin/advertisement-operator"]
        args:
          - "--cluster-id"
          - "$(CLUSTER_ID)"
          - "--kubelet-namespace"
          - "$(POD_NAMESPACE)"
          - "--kubelet-image"
          - {{ .Values.virtualKubelet.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
          - "--init-kubelet-image"
          - {{ .Values.initVk.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: cluster-id
                key: cluster-id
          - name: POD_NAMESPACE
            valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M