---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: auth-service
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  {{ if .Values.authService.ingress.enable }}
  type: ClusterIP
  {{ else }}
  type: NodePort
  {{ end }}
  selector:
    run: auth-service
  ports:
    - name: https
      protocol: TCP
      {{ if .Values.authService.ingress.enable }}
      port: 5000
      targetPort: 5000
      {{ else }}
      port: 443
      targetPort: 443
      {{ end }}