---
{{- $config := (merge (dict "name" "configuration" "module" "configuration") .) -}}

apiVersion: config.liqo.io/v1alpha1
kind: ClusterConfig
metadata:
  name: {{ include "liqo.prefixedName" $config }}
  labels:
    {{- include "liqo.labels" $config  | nindent 4 }}
spec:
  advertisementConfig:
    {{- .Values.advertisement.config | toYaml | nindent 4 }}
  discoveryConfig:
    {{- .Values.discovery.config | toYaml | nindent 4 }}
  authConfig:
    {{- .Values.auth.config | toYaml | nindent 4 }}
  liqonetConfig:
    {{- .Values.networkManager.config | toYaml | nindent 4 }}
  dispatcherConfig:
    resourcesToReplicate:
    - group: net.liqo.io
      version: v1alpha1
      resource: networkconfigs
  agentConfig:
    dashboardConfig:
      namespace: {{ .Release.Namespace }}
      appLabel: "liqo-dashboard"
