---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: crdreplicator-operator
  name: crdreplicator-operator
spec:
  selector:
    matchLabels:
      run: crdreplicator-operator
  template:
    metadata:
      labels:
        run: crdreplicator-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      serviceAccountName: crdreplicator-operator-service-account
      containers:
        - image: {{ .Values.crdReplicator.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: crdreplicator-operator
          command: ["/usr/bin/crd-replicator"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
           limits:
             cpu: 30m
             memory: 50M
           requests:
             cpu: 30m
             memory: 50M
      restartPolicy: Always
---