---
{{- $advertisementConfig := (merge (dict "name" "advertisement" "module" "sharing-protocol") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "liqo.labels" $advertisementConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $advertisementConfig }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $advertisementConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.advertisement.pod.annotations }}
      annotations:
      {{- toYaml .Values.advertisement.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $advertisementConfig | nindent 8 }}
      {{- if .Values.advertisement.pod.labels }}
        {{- toYaml .Values.advertisement.pod.labels | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $advertisementConfig }}
      containers:
      - image: {{ .Values.advertisement.imageName }}{{ include "liqo.suffix" $advertisementConfig }}:{{ include "liqo.version" $advertisementConfig }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: {{ $advertisementConfig.name }}
        command: ["/usr/bin/advertisement-operator"]
        args:
          - "--cluster-id"
          - "$(CLUSTER_ID)"
          - "--liqo-namespace"
          - "$(POD_NAMESPACE)"
          - "--kubelet-image"
          - {{ .Values.virtualKubelet.imageName }}{{ include "liqo.suffix" $advertisementConfig }}:{{ include "liqo.version" $advertisementConfig }}
          - "--init-kubelet-image"
          - {{ .Values.virtualKubelet.initContainer.imageName }}{{ include "liqo.suffix" $advertisementConfig }}:{{ include "liqo.version" $advertisementConfig }}
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: cluster-id
                key: cluster-id
          - name: POD_NAMESPACE
            valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M