{{- $crdReplicatorConfig := (merge (dict "name" "crd-replicator" "module" "dispatcher") .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
  labels:
  {{- include "liqo.labels" $crdReplicatorConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
  labels:
  {{- include "liqo.labels" $crdReplicatorConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
  labels:
    {{- include "liqo.labels" $crdReplicatorConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $crdReplicatorConfig))) }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
  labels:
  {{- include "liqo.labels" $crdReplicatorConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "liqo.prefixedName" $crdReplicatorConfig }}
  labels:
  {{- include "liqo.labels" $crdReplicatorConfig | nindent 4 }}
{{ .Files.Get (include "liqo.role-filename" (dict "prefix" ( include "liqo.prefixedName" $crdReplicatorConfig))) }}
