{{- $fabricConfig := (merge (dict "name" "fabric" "module" "networking" "version" .Values.networking.fabric.image.version ) .) -}}

{{- if .Values.networking.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $fabricConfig }}
  labels:
    {{- include "liqo.labels" $fabricConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $fabricConfig }}
  labels:
    {{- include "liqo.labels" $fabricConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $fabricConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $fabricConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $fabricConfig }}
  labels:
    {{- include "liqo.labels" $fabricConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $fabricConfig))) }}
{{- if .Values.openshiftConfig.enabled }}
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ include "liqo.prefixedName" $fabricConfig }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}

{{- end }}
