---
{{- $authConfig := (merge (dict "name" "auth" "module" "discovery") .) -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $authConfig }}
  labels:
    {{- include "liqo.labels" $authConfig | nindent 4 }}
    {{- include "liqo.authServiceLabels" . | nindent 4 }}
  annotations:
    {{- if .Values.auth.service.annotations }}
    {{- toYaml .Values.auth.service.annotations | nindent 4}}
    {{- end }}
    {{- if .Values.auth.config.addressOverride }}
    liqo.io/override-address: {{ .Values.auth.config.addressOverride | quote }}
    {{- else if .Values.auth.ingress.enable }}
    liqo.io/override-address: {{ .Values.auth.ingress.host | quote }}
    {{- end }}
    {{- if .Values.auth.config.portOverride }}
    liqo.io/override-port: {{ .Values.auth.config.portOverride | quote }}
    {{- else if .Values.auth.ingress.enable }}
    liqo.io/override-port: "443"
    {{- end }}
spec:
  type: {{ .Values.auth.service.type }}
  selector:
    {{- include "liqo.selectorLabels" $authConfig | nindent 4 }}
    {{- include "liqo.authServiceLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      {{- if not .Values.auth.tls }}
      port: 5000
      targetPort: 5000
      {{- else }}
      port: 443
      targetPort: 8443
      {{- end }}
