---
{{- $webhookConfig := (merge (dict "name" (required ".Values.webhook.name is required" .Values.webhook.name) "module" (required ".Values.webhook.module is required" .Values.webhook.module)) .) -}}

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "liqo.prefixedName" $webhookConfig }}
  labels:
    {{- include "liqo.labels" $webhookConfig | nindent 4 }}
    {{- include "liqo.webhookServiceLabels" . | nindent 4 }}
{{- if .Values.webhook.podAnnotations }}
  annotations:
  {{- toYaml .Values.webhook.mutatingWebhookConfiguration.annotations | nindent 8 }}
{{- end }}
webhooks:
  - name: {{ include "liqo.prefixedName" $webhookConfig }}.{{ .Release.Namespace }}.{{ include "liqo.prefixedName" $webhookConfig }}
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: eHh4Cg==
      service:
        name: {{ include "liqo.prefixedName" $webhookConfig }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Ignore
    namespaceSelector:
      matchLabels:
        {{- toYaml .Values.webhook.mutatingWebhookConfiguration.namespaceSelector | nindent 8 }}
