---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: liqo-route-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: liqo-route-manager-role
rules:
  - apiGroups:
      - net.liqo.io
    resources:
      - tunnelendpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - net.liqo.io
    resources:
      - tunnelendpoints/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - config.liqo.io
    resources:
     - clusterconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
     - ""
    resources:
     - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
      - watch
      - update
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: liqo-route-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-route-manager-role
subjects:
  - kind: ServiceAccount
    name: liqo-route-service-account
    namespace: {{ .Release.Namespace }}
