---
{{- $gatewayConfig := (merge (dict "name" (required ".Values.gateway.name is required" .Values.gateway.name) "module" (required ".Values.gateway.module is required" .Values.gateway.module)) .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $gatewayConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.gateway.pod.annotations }}
      annotations:
      {{- toYaml .Values.gateway.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $gatewayConfig | nindent 8 }}
        {{- include "liqo.gatewayPodLabels" . | nindent 8 }}
        {{- if .Values.gateway.pod.labels }}
          {{- toYaml .Values.gateway.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $gatewayConfig }}
      containers:
        - image: {{ .Values.gateway.imageName }}{{ include "liqo.suffix" $gatewayConfig }}:{{ include "liqo.version" $gatewayConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.gateway.name }}
          ports:
          - containerPort: 5871
          command: ["/usr/bin/liqonet"]
          args: ["-run-as=liqo-gateway"]
          resources:
            limits:
              cpu: 10m
              memory: 30M
            requests:
              cpu: 10m
              memory: 30M
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
