---
{{- $routeConfig := (merge (dict "name" "route" "module" "networking") .) -}}

{{- if .Values.networking.internal }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "liqo.labels" $routeConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $routeConfig }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $routeConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.route.pod.annotations }}
      annotations:
        {{- toYaml .Values.route.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.selectorLabels" $routeConfig | nindent 8 }}
        {{- if .Values.route.pod.labels }}
          {{- toYaml .Values.route.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        {{- if .Values.route.tolerations }}
        {{- toYaml .Values.route.tolerations | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "liqo.prefixedName" $routeConfig }}
      containers:
        - image: {{ .Values.route.imageName }}{{ include "liqo.suffix" $routeConfig }}:{{ include "liqo.version" $routeConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ $routeConfig.name }}
          command: ["/usr/bin/liqonet"]
          args:
          - --run-as=liqo-route
          - --route.vxlan-mtu={{ .Values.networking.mtu }}
          {{- if .Values.common.extraArgs }}
          {{- toYaml .Values.common.extraArgs | nindent 10 }}
          {{- end }}
          {{- if .Values.route.pod.extraArgs }}
          {{- toYaml .Values.route.pod.extraArgs | nindent 10 }}
          {{- end }}
          resources: {{- toYaml .Values.route.pod.resources | nindent 12 }}
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
               fieldRef:
                 fieldPath: spec.nodeName
            - name: IPTABLES_MODE
              value: {{ .Values.networking.iptables.mode }}
          volumeMounts:
            - mountPath: /run/xtables.lock
              name: xtables-lock
      hostNetwork: true
      volumes:
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock

{{- end }}
