---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    run: liqo-route
  name: liqo-route
spec:
  selector:
    matchLabels:
      run: liqo-route
  template:
    metadata:
      labels:
        run: liqo-route
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      serviceAccountName: liqo-route-service-account
      containers:
        - image: {{ .Values.networkModule.routeOperator.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: liqo-route
          command: ["/usr/bin/liqonet"]
          args: ["-run-as=liqo-route"]
          resources:
            limits:
              cpu: 100m
              memory: 80M
            requests:
              cpu: 100m
              memory: 80M
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
               fieldRef:
                 fieldPath: spec.nodeName
      hostNetwork: true
      restartPolicy: Always
