---
{{- $routeConfig := (merge (dict "name" (required ".Values.route.name is required" .Values.route.name) "module" (required ".Values.route.module is required" .Values.route.module)) .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $routeConfig }}
  labels:
    {{- include "liqo.labels" $routeConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $routeConfig }}
  labels:
    {{- include "liqo.labels" $routeConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $routeConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $routeConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $routeConfig }}
  labels:
    {{- include "liqo.labels" $routeConfig | nindent 4 }}
{{ .Files.Get (include "liqo.rbac-filename" (dict "prefix" ( include "liqo.prefixedName" $routeConfig))) }}