{{- if and (.Values.networking.enabled) (.Values.networking.legacy) }}

---
{{- $gatewayMetricsConfig := (merge (dict "name" "legacy-gateway-metrics" "module" "networking") .) -}}
{{- if .Values.gateway.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "liqo.prefixedName" $gatewayMetricsConfig }}
  labels:
    {{- include "liqo.labels" $gatewayMetricsConfig | nindent 4 }}
    {{- if .Values.gateway.metrics.serviceMonitor.labels }}
      {{- toYaml .Values.gateway.metrics.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.labels" $gatewayMetricsConfig | nindent 6 }}
  endpoints:
  - port: metrics
    {{- with .Values.gateway.metrics.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.gateway.metrics.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
{{- end }}

{{- end }}
