---
{{- $authConfig := (merge (dict "name" "auth" "module" "discovery" "containerName" "cert-creator") .) -}}
{{- $awsConfig := (merge (dict "name" "aws-config" "module" "aws-config") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $authConfig }}
  labels:
    {{- include "liqo.labels" $authConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $authConfig | nindent 6 }}
      {{- include "liqo.authServiceLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo.selectorLabels" $authConfig | nindent 8 }}
        {{- include "liqo.authServiceLabels" . | nindent 8 }}
      {{- if .Values.auth.pod.labels }}
        {{- toYaml .Values.auth.pod.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.auth.pod.annotations }}
      annotations:
        {{- toYaml .Values.auth.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $authConfig }}
      {{- if .Values.auth.tls }}
      initContainers:
        - name: {{ $authConfig.containerName }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: {{ .Values.auth.initContainer.imageName }}{{ include "liqo.suffix" $authConfig }}:{{ include "liqo.version" $authConfig }}
          volumeMounts:
            - mountPath: '/certs'
              name: certs
          command: [ "/usr/bin/openssl" ]
          args:
            - req
            - -x509
            - -subj
            - /C=IT/ST=Turin/O=Liqo
            - -nodes
            - -days
            - "365"
            - -newkey
            - rsa:4096
            - -keyout
            - /certs/key.pem
            - -out
            - /certs/cert.pem
          resources:
            limits:
              cpu: "1"
              memory: "100M"
            requests:
              cpu: "200m"
              memory: "100M"
      {{- end }}
      containers:
        - image: {{ .Values.auth.imageName }}{{ include "liqo.suffix" $authConfig }}:{{ include "liqo.version" $authConfig }}
          name: {{ $authConfig.name }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/usr/bin/auth-service"]
          args:
          - "--namespace=$(POD_NAMESPACE)"
          - "--resyncSeconds=30"
          {{- if .Values.awsConfig.accessKeyId }}
          - "--awsAccessKeyId=$(ACCESS_KEY_ID)"
          {{- end }}
          {{- if .Values.awsConfig.secretAccessKey }}
          - "--awsSecretAccessKey=$(SECRET_ACCESS_KEY)"
          {{- end }}
          {{- if .Values.awsConfig.region }}
          - "--awsRegion={{ .Values.awsConfig.region }}"
          {{- end }}
          {{- if .Values.awsConfig.clusterName }}
          - "--awsClusterName={{ .Values.awsConfig.clusterName }}"
          {{- end }}
          {{- if not .Values.auth.tls}}
          - "--listeningPort=5000"
          {{- else }}
          - "--listeningPort=443"
          - "--useTls"
          {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.awsConfig.accessKeyId }}
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "liqo.prefixedName" $awsConfig }}
                  key: ACCESS_KEY_ID
            {{- end }}
            {{- if .Values.awsConfig.secretAccessKey }}
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "liqo.prefixedName" $awsConfig }}
                  key: SECRET_ACCESS_KEY
            {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 50M
          volumeMounts:
            - mountPath: '/certs'
              name: certs
      volumes:
        - name: certs
          emptyDir: {}
