---
{{- $authConfig := (merge (dict "name" "auth" "module" "discovery" "containerName" "cert-creator") .) -}}
{{- $awsConfig := (merge (dict "name" "aws-config" "module" "aws-config") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $authConfig }}
  labels:
    {{- include "liqo.labels" $authConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $authConfig | nindent 6 }}
      {{- include "liqo.authServiceLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo.selectorLabels" $authConfig | nindent 8 }}
        {{- include "liqo.authServiceLabels" . | nindent 8 }}
      {{- if .Values.auth.pod.labels }}
        {{- toYaml .Values.auth.pod.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.auth.pod.annotations }}
      annotations:
        {{- toYaml .Values.auth.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- include "liqo.podSecurityContext" . | nindent 8 }}
      serviceAccountName: {{ include "liqo.prefixedName" $authConfig }}
      {{- if .Values.auth.tls }}
      initContainers:
        - name: {{ $authConfig.containerName }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          securityContext:
            {{- include "liqo.containerSecurityContext" . | nindent 12 }}
          image: {{ .Values.auth.initContainer.imageName }}{{ include "liqo.suffix" $authConfig }}:{{ include "liqo.version" $authConfig }}
          volumeMounts:
            - mountPath: '/certs'
              name: certs
          command: [ "/usr/bin/openssl" ]
          args:
            - req
            - -x509
            - -subj
            - /C=IT/ST=Turin/O=Liqo
            - -nodes
            - -days
            - "365"
            - -newkey
            - rsa:4096
            - -keyout
            - /certs/key.pem
            - -out
            - /certs/cert.pem
          resources: {{- toYaml .Values.auth.pod.resources | nindent 12 }}
      {{- end }}
      containers:
        - image: {{ .Values.auth.imageName }}{{ include "liqo.suffix" $authConfig }}:{{ include "liqo.version" $authConfig }}
          securityContext:
            {{- include "liqo.containerSecurityContext" . | nindent 12 }}
          name: {{ $authConfig.name }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/usr/bin/auth-service"]
          args:
          - --cluster-id=$(CLUSTER_ID)
          - --cluster-name={{ .Values.discovery.config.clusterName }}
          - --namespace=$(POD_NAMESPACE)
          {{- if not .Values.auth.tls}}
          - --address=:5000
          {{- else }}
          - --address=:8443
          - --enable-tls
          {{- end }}
          - --enable-authentication={{ .Values.auth.config.enableAuthentication }}
          {{- if .Values.apiServer.address }}
          - --advertise-api-server-address={{ .Values.apiServer.address }}
          {{- end }}
          {{- if .Values.apiServer.trustedCA }}
          - --advertise-api-server-trusted-ca
          {{- end }}
          {{- if .Values.awsConfig.accessKeyId }}
          - --aws-access-key-id=$(ACCESS_KEY_ID)
          {{- end }}
          {{- if .Values.awsConfig.secretAccessKey }}
          - --aws-secret-access-key=$(SECRET_ACCESS_KEY)
          {{- end }}
          {{- if .Values.awsConfig.region }}
          - --aws-region={{ .Values.awsConfig.region }}
          {{- end }}
          {{- if .Values.awsConfig.clusterName }}
          - --aws-cluster-name={{ .Values.awsConfig.clusterName }}
          {{- end }}
          {{- if .Values.common.extraArgs }}
          {{- toYaml .Values.common.extraArgs | nindent 10 }}
          {{- end }}
          {{- if .Values.auth.pod.extraArgs }}
          {{- toYaml .Values.auth.pod.extraArgs | nindent 10 }}
          {{- end }}
          env:
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "liqo.clusterIdConfig" . }}
                  key: CLUSTER_ID
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.awsConfig.accessKeyId }}
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "liqo.prefixedName" $awsConfig }}
                  key: ACCESS_KEY_ID
            {{- end }}
            {{- if .Values.awsConfig.secretAccessKey }}
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "liqo.prefixedName" $awsConfig }}
                  key: SECRET_ACCESS_KEY
            {{- end }}
          resources: {{- toYaml .Values.auth.pod.resources | nindent 12 }}
          volumeMounts:
            - mountPath: '/certs'
              name: certs
      volumes:
        - name: certs
          emptyDir: {}
      {{- if ((.Values.common).nodeSelector) }}
      nodeSelector:
      {{- toYaml .Values.common.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).tolerations) }}
      tolerations:
      {{- toYaml .Values.common.tolerations | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).affinity) }}
      affinity:
      {{- toYaml .Values.common.affinity | nindent 8 }}
      {{- end }}
