{{- $authConfig := (merge (dict "name" "auth" "module" "discovery") .) -}}

  {{- if .Values.auth.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "liqo.prefixedName" $authConfig }}
  labels:
    {{- include "liqo.labels" $authConfig | nindent 4 }}
  {{- if or .Values.auth.ingress.annotations .Values.auth.ingress.class}}
  annotations:
  {{- if .Values.auth.ingress.annotations }}
    {{- toYaml .Values.auth.ingress.annotations | nindent 4}}
  {{- end }}
  {{- end}}
spec:
  {{- if .Values.auth.ingress.class }}
  ingressClassName: {{ .Values.auth.ingress.class }}
  {{- end }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ include "liqo.prefixedName" $authConfig }}
                port:
                {{- if not .Values.auth.tls}}
                  number: 5000
                {{- else }}
                  number: 443
                {{- end }}
            path: /
            pathType: Prefix
      {{- if .Values.auth.ingress.host }}
      host: {{ .Values.auth.ingress.host }}
      {{- end }}
  tls:
    {{- if .Values.auth.ingress.host }}
    - hosts:
      - {{ .Values.auth.ingress.host }}
      {{- if .Values.auth.ingress.tlsSecretName }}
      secretName: {{ .Values.auth.ingress.tlsSecretName }}
      {{- else }}
      secretName: {{ include "liqo.prefixedName" $authConfig }}
      {{- end}}
    {{- else }}
    - hosts: []
    {{- end }}
{{- end }}
