---
{{- $proxyConfig := (merge (dict "name" "proxy" "module" "networking") .) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liqo.prefixedName" $proxyConfig }}
{{- if .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml .Values.proxy.service.annotations | nindent 4 }}
{{- end}}
  labels:
    {{- include "liqo.labels" $proxyConfig | nindent 4 }}
data:
  config: |
    admin:
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901
    static_resources:
     listeners:
       - name: listener_http
         address:
           socket_address:
             protocol: TCP
             address: 0.0.0.0
             port_value: {{ .Values.proxy.config.listeningPort }}
         access_log:
           name: envoy.access_loggers.file
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
             path: /dev/stdout
         filter_chains:
           - filters:
               - name: envoy.filters.network.http_connection_manager
                 typed_config:
                   "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                   stat_prefix: ingress_http
                   route_config:
                     name: local_route
                     virtual_hosts:
                       - name: local_service
                         domains:
                           - "*"
                         routes:
                           - match:
                               connect_matcher:
                                 {}
                             route:
                               cluster: api_server
                               upgrade_configs:
                                 - upgrade_type: CONNECT
                                   connect_config:
                                     {}
                   http_filters:
                     - name: envoy.filters.http.router
                       typed_config:
                         "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
     clusters:
       - name: api_server
         connect_timeout: 1.25s
         type: STRICT_DNS
         respect_dns_ttl: true
         dns_lookup_family: V4_ONLY
         dns_refresh_rate: 300s
         lb_policy: ROUND_ROBIN
         load_assignment:
           cluster_name: api_server
           endpoints:
             - lb_endpoints:
                 - endpoint:
                     address:
                       socket_address:
                         address: kubernetes.default
                         port_value: 443
