{{- if or .Values.discovery.config.enableAdvertisement .Values.discovery.config.enableDiscovery }}

---
{{- $discoveryConfig := (merge (dict "name" "discovery" "module" "discovery") .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  labels:
  {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $discoveryConfig}}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  labels:
  {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $discoveryConfig}}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  labels:
  {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $discoveryConfig))) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  labels:
  {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
{{ .Files.Get (include "liqo.role-filename" (dict "prefix" ( include "liqo.prefixedName" $discoveryConfig))) }}

{{- end }}
