---
{{- $fabricConfig := (merge (dict "name" "fabric" "module" "networking" "version" .Values.networking.fabric.image.version ) .) -}}

{{- if .Values.networking.enabled }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "liqo.labels" $fabricConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $fabricConfig }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $fabricConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.networking.fabric.pod.annotations }}
      annotations:
        {{- toYaml .Values.networking.fabric.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.selectorLabels" $fabricConfig | nindent 8 }}
        {{- if .Values.networking.fabric.pod.labels }}
          {{- toYaml .Values.networking.fabric.pod.labels | nindent 8 }}
        {{- end }}
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        {{- if .Values.networking.fabric.tolerations }}
        {{- toYaml .Values.networking.fabric.tolerations | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "liqo.prefixedName" $fabricConfig }}
      containers:
        - image: {{ .Values.networking.fabric.image.name }}{{ include "liqo.suffix" $fabricConfig }}:{{ include "liqo.version" $fabricConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ $fabricConfig.name }}
          command: ["/usr/bin/liqo-fabric"]
          args:
          - --podname=$(POD_NAME)
          - --nodename=$(NODE_NAME)
          - --geneve-port={{ .Values.networking.genevePort }}
          {{- if not .Values.requirements.kernel.enabled }}
          - --disable-kernel-version-check
          {{- end }}
          - --enable-nft-monitor={{ .Values.networking.fabric.config.nftablesMonitor }}
          {{- if .Values.common.globalAnnotations }}
          {{- $d := dict "commandName" "--global-annotations" "dictionary" .Values.common.globalAnnotations -}}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.common.globalLabels }}
          {{- $d := dict "commandName" "--global-labels" "dictionary" .Values.common.globalLabels -}}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.common.extraArgs }}
          {{- toYaml .Values.common.extraArgs | nindent 10 }}
          {{- end }}
          {{- if .Values.networking.fabric.pod.extraArgs }}
          {{- toYaml .Values.networking.fabric.pod.extraArgs | nindent 10 }}
          {{- end }}
          resources: {{- toYaml .Values.networking.fabric.pod.resources | nindent 12 }}
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      hostNetwork: true
      {{- if .Values.networking.fabric.pod.priorityClassName }}
      priorityClassName: {{ .Values.networking.fabric.pod.priorityClassName }}
      {{- end }}

{{- end }}
