---
{{- $ipamConfig := (merge (dict "name" "ipam" "module" "ipam") .) -}}

{{- if and (.Values.networking.internal) (not .Values.ipam.external.enabled) (not .Values.ipam.legacy ) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $ipamConfig }}
  labels:
    {{- include "liqo.labels" $ipamConfig | nindent 4 }}
spec:
  # This service is made to be consumed within the cluster.
  type: ClusterIP
  ports:
    - name: ipam-api
      port: 6000
      protocol: TCP
  selector:
    {{- include "liqo.selectorLabels" $ipamConfig | nindent 4 }}

{{- end }}
