{{- $peeringroles := (merge (dict "name" "peering-user" "module" "peering-user") .) -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $peeringroles}}
  labels:
  {{- include "liqo.labels" $peeringroles| nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $peeringroles))) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "liqo.prefixedName" $peeringroles}}
  labels:
  {{- include "liqo.labels" $peeringroles| nindent 4 }}
{{ .Files.Get (include "liqo.role-filename" (dict "prefix" ( include "liqo.prefixedName" $peeringroles))) }}