---
{{- $gatewayConfig := (merge (dict "name" "gateway" "module" "networking") .) -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
{{- if .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml .Values.gateway.service.annotations | nindent 4 }}
{{- end}}
  labels:
    {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
    {{- include "liqo.gatewayServiceLabels" $gatewayConfig | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: wireguard
      port: {{ .Values.gateway.config.listeningPort }}
      targetPort: wireguard
      protocol: UDP
  selector:
    {{- include "liqo.gatewaySelector" $gatewayConfig | nindent 4 }}
