{{- $virtualKubeletConfig := (merge (dict "name" "virtual-kubelet-local" "module" "virtualkubelet") .) -}}

# to be enabled with the creation of the Tenant Namespace,
# this ClusterRole has the basic permissions to give to a remote cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $virtualKubeletConfig }}
  labels:
    {{- include "liqo.labels" $virtualKubeletConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $virtualKubeletConfig))) }}
{{- if and (.Values.openshiftConfig.enable) (gt (len .Values.openshiftConfig.virtualKubeletSCCs) 0) -}}
- apiGroups:
  - security.openshift.io
  resourceNames:
{{- range $scc := .Values.openshiftConfig.virtualKubeletSCCs }}
  - {{ $scc }}
{{- end }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}
