---
{{- $webhookConfig := (merge (dict "name" (required ".Values.webhook.name is required" .Values.webhook.name) "module" (required ".Values.webhook.module is required" .Values.webhook.module)) .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $webhookConfig }}
  labels:
    {{- include "liqo.labels" $webhookConfig | nindent 4 }}
    {{- include "liqo.webhookServiceLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $webhookConfig | nindent 6 }}
      {{- include "liqo.webhookServiceLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo.labels" $webhookConfig | nindent 8 }}
        {{- include "liqo.webhookServiceLabels" . | nindent 8 }}
      {{- if .Values.webhook.pod.labels }}
        {{- toYaml .Values.webhook.pod.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.webhook.pod.annotations }}
      annotations:
        {{- toYaml .Values.webhook.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $webhookConfig }}
      initContainers:
        - name: {{ .Values.webhook.initContainer.name }}
          image: {{ .Values.webhook.initContainer.imageName}}{{ include "liqo.suffix" $webhookConfig }}:{{ include "liqo.version" $webhookConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          args:
            - "--webhook-name"
            - {{ include "liqo.prefixedName" $webhookConfig }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - mountPath: /etc/ssl/liqo
              name: cert-volume
          resources:
            limits:
              cpu: "1"
              memory: "100M"
            requests:
              cpu: "200m"
              memory: "100M"
      containers:
        - name: {{ .Values.webhook.name }}
          image: {{ .Values.webhook.imageName }}{{ include "liqo.suffix" $webhookConfig }}:{{ include "liqo.version" $webhookConfig }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/ssl/liqo
              name: cert-volume
          resources:
            limits:
              cpu: 100m
              memory: 50M
            requests:
              cpu: 100m
              memory: 50M
      volumes:
        - name: cert-volume
          emptyDir: {}