---
{{- $authConfig := (merge (dict "name" (required ".Values.auth.name is required" .Values.auth.name) "module" (required ".Values.auth.module is required" .Values.auth.module)) .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $authConfig }}
  labels:
    {{- include "liqo.labels" $authConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $authConfig | nindent 6 }}
      {{- include "liqo.authServiceLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo.selectorLabels" $authConfig | nindent 8 }}
        {{- include "liqo.authServiceLabels" . | nindent 8 }}
        {{- if .Values.auth.podLabels }}
        {{- toYaml .Values.auth.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.auth.podAnnotations }}
      annotations:
        {{- toYaml .Values.auth.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $authConfig }}
      {{- if not .Values.auth.ingress.enable }}
      initContainers:
        - name: cert-creator
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: nginx:1.19
          volumeMounts:
            - mountPath: '/certs'
              name: certs
          command: [ "/bin/sh" ]
          args: [ "-c", 'openssl req -x509 -subj "/C=IT/ST=Turin/O=Liqo" -nodes -days 365 -newkey rsa:4096 -keyout /certs/key.pem -out /certs/cert.pem' ]
      {{- end }}
      containers:
        - image: {{ .Values.auth.imageName }}{{ default .Values.suffix }}:{{ default .Values.version }}
          name: auth-service
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/usr/bin/auth-service"]
          args:
          - "--namespace"
          - "$(POD_NAMESPACE)"
          - "--resyncSeconds"
          - "30"
          - "--listeningPort"
          {{- if .Values.auth.ingress.enable }}
          - "5000"
          {{- else }}
          - "443"
          - "--useTls"
          {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.apiServer.ip }}
            - name: APISERVER
              value: "{{ .Values.apiServer.ip }}"
            {{- end }}
            {{- if .Values.apiServer.port  }}
            - name: APISERVER_PORT
              value: "{{ .Values.apiServer.port }}"
            {{- end }}
          resources:
            limits:
              cpu: 50m
              memory: 50M
            requests:
              cpu: 50m
              memory: 50M
          volumeMounts:
            - mountPath: '/certs'
              name: certs
      volumes:
        - name: certs
          emptyDir: {}