---
{{- $discoveryConfig := (merge (dict "name" (required ".Values.discovery.name is required" .Values.discovery.name) "module" (required ".Values.discovery.module is required" .Values.discovery.module)) .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $discoveryConfig}}
  labels:
    {{- include "liqo.labels" $discoveryConfig| nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.labels" $discoveryConfig| nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "liqo.labels" $discoveryConfig| nindent 8 }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $discoveryConfig}}
      containers:
        - image: {{ .Values.discoveryOperator.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
          name: discovery
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/usr/bin/entrypoint.sh", "/usr/bin/discovery"]
          args:
          - "--namespace"
          - "$(POD_NAMESPACE)"
          - "--requeueAfter"
          - "30"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.apiServer.ip }}
            - name: APISERVER
              value: "{{ .Values.apiServer.ip }}"
            {{- end }}
            {{- if .Values.apiServer.port }}
            - name: APISERVER_PORT
              value: "{{ .Values.apiServer.port }}"
            {{- end }}
            {{- if .Values.authServer.ip }}
            - name: AUTH_ADDR
              value: "{{ .Values.authServer.ip }}"
            {{- end }}
            {{- if .Values.authServer.port }}
            - name: AUTH_SVC_PORT
              value: "{{ .Values.authServer.port }}"
            {{- end }}
          resources:
            limits:
              cpu: 50m
              memory: 50M
            requests:
              cpu: 50m
              memory: 50M
      hostNetwork: true
