---
{{- $ipamConfig := (merge (dict "name" "ipam" "module" "ipam") .) -}}

{{- if and (.Values.networking.internal) (not .Values.ipam.external.enabled) (not .Values.ipam.legacy ) }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $ipamConfig }}
  labels:
  {{- include "liqo.labels" $ipamConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ipamConfig }}
  labels:
  {{- include "liqo.labels" $ipamConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $ipamConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ipamConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $ipamConfig }}
  labels:
  {{- include "liqo.labels" $ipamConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $ipamConfig))) }}

{{- end }}