---
{{- $webhookConfig := (merge (dict "name" "webhook" "module" "webhook") .) -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $webhookConfig }}
  labels:
    {{- include "liqo.labels" $webhookConfig | nindent 4 }}
    {{- include "liqo.webhookServiceLabels" . | nindent 4 }}
  {{- if .Values.webhook.service.annotations }}
  annotations:
    {{- toYaml .Values.webhook.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "liqo.selectorLabels" $webhookConfig | nindent 4 }}
    {{- include "liqo.webhookServiceLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443