---
{{- $awsConfig := (merge (dict "name" "aws-config" "module" "aws-config") .) -}}

{{- if and .Values.authentication.awsConfig.accessKeyId .Values.authentication.awsConfig.secretAccessKey (not .Values.authentication.awsConfig.useExistingSecret) }}

apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "liqo.labels" $awsConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $awsConfig }}
data:
    ACCESS_KEY_ID: {{ .Values.authentication.awsConfig.accessKeyId | b64enc }}
    SECRET_ACCESS_KEY: {{ .Values.authentication.awsConfig.secretAccessKey | b64enc }}

{{- end }}
