---
{{- $gatewayConfig := (merge (dict "name" "legacy-gateway" "module" "networking") .) -}}

{{- if .Values.networking.internal }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
  annotations:
    {{- if .Values.gateway.service.annotations }}
    {{- toYaml .Values.gateway.service.annotations | nindent 4 }}
    {{- end}}
    {{- if .Values.gateway.config.addressOverride }}
    liqo.io/override-address: {{ .Values.gateway.config.addressOverride | quote }}
    {{- end }}
    {{- if .Values.gateway.config.portOverride }}
    liqo.io/override-port: {{ .Values.gateway.config.portOverride | quote }}
    {{- end }}
  labels:
    {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
    {{- include "liqo.gatewayServiceLabels" $gatewayConfig | nindent 4 }}
    {{- if .Values.gateway.service.labels }}
      {{- toYaml .Values.gateway.service.labels | nindent 4 }}
    {{- end}}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: wireguard
      port: {{ .Values.gateway.config.listeningPort }}
      targetPort: wireguard
      protocol: UDP
      {{- if and (eq .Values.gateway.service.type "NodePort") (.Values.gateway.service.nodePort.port) }}
      nodePort: {{ .Values.gateway.service.nodePort.port }}
      {{- end }}
  {{- if and (eq .Values.gateway.service.type "LoadBalancer") (.Values.gateway.service.loadBalancer.ip) }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancer.ip }}
  {{- end }}
  {{- if and (eq .Values.gateway.service.type "LoadBalancer") (.Values.gateway.service.loadBalancer.allocateLoadBalancerNodePorts) }}
  allocateLoadBalancerNodePorts: {{ .Values.gateway.service.loadBalancer.allocateLoadBalancerNodePorts }}
  {{- end }}
  selector:
    {{- include "liqo.gatewaySelector" $gatewayConfig | nindent 4 }}

---
{{- $gatewayMetricsConfig := (merge (dict "name" "gateway-metrics" "module" "networking") .) -}}

{{- if .Values.gateway.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $gatewayMetricsConfig }}
  annotations:
    {{- if .Values.gateway.metrics.service.annotations }}
      {{- toYaml .Values.gateway.metrics.service.annotations | nindent 4 }}
    {{- end}}
  labels:
    {{- include "liqo.labels" $gatewayMetricsConfig | nindent 4 }}
    {{- if .Values.gateway.metrics.service.labels }}
      {{- toYaml .Values.gateway.metrics.service.labels | nindent 4 }}
    {{- end}}
spec:
  selector:
    {{- include "liqo.gatewaySelector" $gatewayMetricsConfig | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.gateway.metrics.port }}
      targetPort: metrics
{{- end}}

{{- end }}
