---
{{- $ctrlManagerConfig := (merge (dict "name" "controller-manager" "module" "controller-manager") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $ctrlManagerConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.controllerManager.pod.annotations }}
      annotations:
      {{- toYaml .Values.controllerManager.pod.annotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $ctrlManagerConfig | nindent 8 }}
      {{- if .Values.controllerManager.pod.labels }}
        {{- toYaml .Values.controllerManager.pod.labels | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- include "liqo.podSecurityContext" . | nindent 8 }}
      serviceAccountName: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
      containers:
      - image: {{ .Values.controllerManager.imageName }}{{ include "liqo.suffix" $ctrlManagerConfig }}:{{ include "liqo.version" $ctrlManagerConfig }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        securityContext:
          {{- include "liqo.containerSecurityContext" . | nindent 10 }}
        name: {{ $ctrlManagerConfig.name }}
        command: ["/usr/bin/liqo-controller-manager"]
        args:
          - --cluster-id=$(CLUSTER_ID)
          - --cluster-name={{ .Values.discovery.config.clusterName }}
          - --liqo-namespace=$(POD_NAMESPACE)
          - --enable-incoming-peering={{ .Values.discovery.config.incomingPeeringEnabled }}
          - --resource-sharing-percentage={{ .Values.controllerManager.config.resourceSharingPercentage }}
          - --kubelet-image={{ .Values.virtualKubelet.imageName }}{{ include "liqo.suffix" $ctrlManagerConfig }}:{{ include "liqo.version" $ctrlManagerConfig }}
          - --init-kubelet-image={{ .Values.virtualKubelet.initContainer.imageName }}{{ include "liqo.suffix" $ctrlManagerConfig }}:{{ include "liqo.version" $ctrlManagerConfig }}
          - --auto-join-discovered-clusters={{ .Values.discovery.config.autojoin }}
          - --enable-storage={{ .Values.storage.enable }}
          {{- if .Values.storage.enable }}
          - --virtual-storage-class-name={{ .Values.storage.virtualStorageClassName }}
          - --real-storage-class-name={{ .Values.storage.realStorageClassName }}
          - --storage-namespace={{ .Values.storage.storageNamespace }}
          {{- end }}
          {{- if .Values.auth.ingress.enable }}
          - --auth-service-address-override={{ .Values.auth.ingress.host }}
          {{- end }}
          {{- if .Values.auth.portOverride }}
          - --auth-service-port-override={{ .Values.auth.portOverride }}
          {{- else if .Values.auth.ingress.enable }}
          - --auth-service-port-override=443
          {{- end }}
          {{- if .Values.virtualKubelet.extra.annotations }}
          {{- $d := dict "commandName" "--kubelet-extra-annotations" "dictionary" .Values.virtualKubelet.extra.annotations }}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualKubelet.extra.labels }}
          {{- $d := dict "commandName" "--kubelet-extra-labels" "dictionary" .Values.virtualKubelet.extra.labels }}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualKubelet.extra.args }}
          {{- $d := dict "commandName" "--kubelet-extra-args" "list" .Values.virtualKubelet.extra.args }}
          {{- include "liqo.concatenateList" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualKubelet.virtualNode.extra.annotations }}
          {{- $d := dict "commandName" "--node-extra-annotations" "dictionary" .Values.virtualKubelet.virtualNode.extra.annotations }}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.virtualKubelet.virtualNode.extra.labels }}
          {{- $d := dict "commandName" "--node-extra-labels" "dictionary" .Values.virtualKubelet.virtualNode.extra.labels }}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
          {{- if .Values.controllerManager.pod.extraArgs }}
          {{- toYaml .Values.controllerManager.pod.extraArgs | nindent 10 }}
          {{- end }}
          {{- if .Values.discovery.config.clusterLabels }}
          {{- $d := dict "commandName" "--cluster-labels" "dictionary" .Values.discovery.config.clusterLabels }}
          {{- include "liqo.concatenateMap" $d | nindent 10 }}
          {{- end }}
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: {{ include "liqo.clusterIdConfig" . }}
                key: CLUSTER_ID
          - name: POD_NAMESPACE
            valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 150M
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
