{{- $authConfig := (merge (dict "name" "auth" "module" "discovery") .) -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "liqo.prefixedName" $authConfig }}
  labels:
    {{- include "liqo.labels" $authConfig | nindent 4 }}
    {{- include "liqo.authServiceLabels" . | nindent 4 }}
    {{- if .Values.auth.service.labels }}
      {{- toYaml .Values.auth.service.labels | nindent 4}}
    {{- end }}
  annotations:
    {{- if .Values.auth.service.annotations }}
      {{- toYaml .Values.auth.service.annotations | nindent 4}}
    {{- end }}
    {{- if .Values.auth.config.addressOverride }}
    liqo.io/override-address: {{ .Values.auth.config.addressOverride | quote }}
    {{- else if .Values.auth.ingress.enable }}
    liqo.io/override-address: {{ .Values.auth.ingress.host | quote }}
    {{- end }}
    {{- if .Values.auth.config.portOverride }}
    liqo.io/override-port: {{ .Values.auth.config.portOverride | quote }}
    {{- else if .Values.auth.ingress.enable }}
    liqo.io/override-port: {{ .Values.auth.ingress.port | quote }}
    {{- end }}
spec:
  type: {{ .Values.auth.service.type }}
  selector:
    {{- include "liqo.selectorLabels" $authConfig | nindent 4 }}
    {{- include "liqo.authServiceLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      {{- if not .Values.auth.tls }}
      port: 5000
      targetPort: 5000
      {{- else }}
      port: {{ .Values.auth.service.port }}
      targetPort: 8443
      {{- end }}
      {{- if and (eq .Values.auth.service.type "NodePort") (.Values.auth.service.nodePort.port) }}
      nodePort: {{ .Values.auth.service.nodePort.port }}
      {{- end }}
  {{- if and (eq .Values.auth.service.type "LoadBalancer") (.Values.auth.service.loadBalancer.ip) }}
  loadBalancerIP: {{ .Values.auth.service.loadBalancer.ip }}
  {{- end }}
  {{- if and (eq .Values.auth.service.type "LoadBalancer") (.Values.auth.service.loadBalancer.allocateLoadBalancerNodePorts) }}
  allocateLoadBalancerNodePorts: {{ .Values.auth.service.loadBalancer.allocateLoadBalancerNodePorts }}
  {{- end }}
