{{- $ctrlManagerConfig := (merge (dict "name" "controller-manager" "module" "controller-manager") .) -}}
{{- $gatewayConfig := (merge (dict "name" "gateway" "module" "networking") .) -}}
{{- $virtualKubeletConfigLocal := (merge (dict "name" "virtual-kubelet-local" "module" "virtualkubelet") .) -}}
{{- $virtualKubeletConfigRemote := (merge (dict "name" "virtual-kubelet-remote" "module" "virtualkubelet") .) -}}
{{- $virtualKubeletConfigRemoteClusterwide := (merge (dict "name" "virtual-kubelet-remote-clusterwide" "module" "virtualkubelet") .) -}}
{{- $controlPlaneConfig := (merge (dict "name" "remote-controlplane" "module" "authentication") .) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
---
# The controller-manager needs to be also granted the wireguard gateway permissions,
# as it needs to create the necessary cluster role binding associated with the wireguard gateway.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}-grant-wg-gateway
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
---
# The controller-manager needs to be also granted the local virtual kubelet permissions,
# as it needs to create the necessary cluster role binding associated with the virtual kubelet.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}-grant-virtual-kubelet-local
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $virtualKubeletConfigLocal }}
---
# The controller-manager needs to be also granted the remote virtual kubelet permissions,
# as it needs to create the necessary role binding in reflected namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}-grant-virtual-kubelet-remote
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $virtualKubeletConfigRemote }}
---
# The controller-manager needs to be also granted the remote virtual kubelet permissions,
# as it needs to create the necessary role binding in reflected namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}-grant-virtual-kubelet-remote-clusterwide
  labels:
    {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $virtualKubeletConfigRemoteClusterwide }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
  labels:
  {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $ctrlManagerConfig))) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
  labels:
  {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
  labels:
  {{- include "liqo.labels" $ctrlManagerConfig | nindent 4 }}
{{ .Files.Get (include "liqo.role-filename" (dict "prefix" ( include "liqo.prefixedName" $ctrlManagerConfig))) }}
