---
{{- $gatewayConfig := (merge (dict "name" "gateway" "module" "networking") .) -}}

{{- if .Values.networking.internal }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
  labels:
    {{- include "liqo.labels" $gatewayConfig | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
  labels:
    {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $gatewayConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
  labels:
    {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $gatewayConfig))) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
  labels:
  {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $gatewayConfig }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "liqo.prefixedName" $gatewayConfig }}
  labels:
  {{- include "liqo.labels" $gatewayConfig | nindent 4 }}
{{ .Files.Get (include "liqo.role-filename" (dict "prefix" ( include "liqo.prefixedName" $gatewayConfig))) }}
{{- if .Values.openshiftConfig.enable }}
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}

{{- end }}
