{{- $ipamConfig := (merge (dict "name" "ipam" "module" "ipam") .) -}}
---
apiVersion: ipam.liqo.io/v1alpha1
kind: Network
metadata:
  name: pod-cidr
  labels:
    {{- include "liqo.labels" $ipamConfig | nindent 4 }}
    ipam.liqo.io/network-type: pod-cidr
    ipam.liqo.io/network-not-remapped: "true"
  annotations:
    liqo.io/preinstalled: "true"
spec:
  cidr: {{ .Values.ipam.podCIDR }}
---
apiVersion: ipam.liqo.io/v1alpha1
kind: Network
metadata:
  name: service-cidr
  labels:
    {{- include "liqo.labels" $ipamConfig | nindent 4 }}
    ipam.liqo.io/network-type: service-cidr
    ipam.liqo.io/network-not-remapped: "true"
  annotations:
    liqo.io/preinstalled: "true"
spec:
  cidr: {{ .Values.ipam.serviceCIDR }}
---
apiVersion: ipam.liqo.io/v1alpha1
kind: Network
metadata:
  name: external-cidr
  labels:
    {{- include "liqo.labels" $ipamConfig | nindent 4 }}
    ipam.liqo.io/network-type: external-cidr
  annotations:
    liqo.io/preinstalled: "true"
spec:
  cidr: {{ .Values.ipam.externalCIDR }}
  preAllocated: 1 # the first IP of the external CIDR is reserved for the unknown source traffic
---
apiVersion: ipam.liqo.io/v1alpha1
kind: Network
metadata:
  name: internal-cidr
  labels:
    {{- include "liqo.labels" $ipamConfig | nindent 4 }}
    ipam.liqo.io/network-type: internal-cidr
  annotations:
    liqo.io/preinstalled: "true"
spec:
  cidr: {{ .Values.ipam.internalCIDR }}
---
{{- range $i, $value := .Values.ipam.reservedSubnets }}
apiVersion: ipam.liqo.io/v1alpha1
kind: Network
metadata:
  name: reserved-{{ add $i 1 }}
  labels:
    {{- include "liqo.labels" $ipamConfig | nindent 4 }}
    ipam.liqo.io/network-type: reserved
    ipam.liqo.io/network-not-remapped: "true"
  annotations:
    liqo.io/preinstalled: "true"
spec:
  cidr: {{ $value }}
---
{{- end }}
