---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmutator
  labels:
    app: mutatepodtoleration
spec:
  selector:
    matchLabels:
      app: mutatepodtoleration
  template:
    metadata:
      labels:
        app: mutatepodtoleration
    spec:
      serviceAccountName: podmutatoraccount
      initContainers:
      - name: secret-creation
        image: {{ .Values.podMutator.secretCreation.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
          - "--namespace"
          - {{ .Release.Namespace }}
          - "--service"
          - "mutatepodtoleration"
          - "--secret"
          - "pod-mutator-secret"
          - "--export-env-vars"
          - "--output-env-file"
          - "/etc/environment/liqo/env"
          - "--output-dir"
          - "/etc/ssl/liqo"
        volumeMounts:
          - mountPath: /etc/ssl/liqo
            name: certs-volume
          - mountPath: /etc/environment/liqo
            name: env-volume
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
      - name: pod-mutator-deployment
        image: {{ .Values.podMutator.initMutatingWebhook.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
          - "--input-env-file"
          - "/etc/environment/liqo/env"
        volumeMounts:
          - mountPath: /etc/environment/liqo
            name: env-volume
        resources:
          limits:
            cpu: 100m
            memory: 150M
          requests:
            cpu: 100m
            memory: 150M
      containers:
      - name: podmutator
        image: {{ .Values.podMutator.mutatingWebhook.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
          - "--input-env-file"
          - "/etc/environment/liqo/env"
        volumeMounts:
        - mountPath: /etc/ssl/liqo
          name: certs-volume
        - mountPath: /etc/environment/liqo
          name: env-volume
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M
      volumes:
        - name: certs-volume
          emptyDir: {}
        - name: env-volume
          emptyDir: {}
