{{- $predelete := (merge (dict "name" "pre-delete" "module" "pre-delete") .) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liqo.prefixedName" $predelete}}
  labels:
  {{- include "liqo.labels" $predelete| nindent 4 }}
  annotations:
    {{- include "liqo.preDeleteAnnotations" $predelete| nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "liqo.prefixedName" $predelete}}
  labels:
  {{- include "liqo.labels" $predelete| nindent 4 }}
  annotations:
  {{- include "liqo.preDeleteAnnotations" $predelete| nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "liqo.prefixedName" $predelete}}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "liqo.prefixedName" $predelete}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "liqo.prefixedName" $predelete}}
  labels:
  {{- include "liqo.labels" $predelete| nindent 4 }}
  annotations:
  {{- include "liqo.preDeleteAnnotations" $predelete| nindent 4 }}
{{ .Files.Get (include "liqo.cluster-role-filename" (dict "prefix" ( include "liqo.prefixedName" $predelete))) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "liqo.prefixedName" $predelete}}
  labels:
  {{- include "liqo.labels" $predelete| nindent 4 }}
  annotations:
  {{- include "liqo.preDeleteAnnotations" $predelete| nindent 4 }}
{{ .Files.Get (include "liqo.role-filename" (dict "prefix" ( include "liqo.prefixedName" $predelete))) }}
