{{- $predelete := (merge (dict "name" "pre-delete" "module" "pre-delete") .) -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "liqo.prefixedName" $predelete }}
  labels:
    {{- include "liqo.labels" $predelete| nindent 4 }}
  annotations:
    {{- include "liqo.preDeleteAnnotations" $predelete| nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "liqo.prefixedName" $predelete }}
      labels:
        {{- include "liqo.labels" $predelete| nindent 8 }}
    spec:
      securityContext:
        {{- include "liqo.podSecurityContext" . | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: {{ include "liqo.prefixedName" $predelete}}
      containers:
      - name: pre-delete-job
        image: "liqo/uninstaller{{ include "liqo.suffix" $predelete }}:{{ include "liqo.version" $predelete }}"
        securityContext:
          {{- include "liqo.containerSecurityContext" . | nindent 10 }}
        command: ["/usr/bin/uninstaller"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
