{{- $predelete := (merge (dict "name" "pre-delete" "module" "pre-delete") .) -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "liqo.prefixedName" $predelete }}
  labels:
    {{- include "liqo.labels" $predelete| nindent 4 }}
  annotations:
    {{- include "liqo.preDeleteAnnotations" $predelete| nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "liqo.prefixedName" $predelete }}
      labels:
        {{- include "liqo.labels" $predelete| nindent 8 }}
        {{- if .Values.uninstaller.pod.labels }}
        {{- toYaml .Values.uninstaller.pod.labels | nindent 8 }}
        {{- end }}
      {{- if .Values.uninstaller.pod.annotations }}
      annotations:
        {{- toYaml .Values.uninstaller.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- include "liqo.podSecurityContext" . | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: {{ include "liqo.prefixedName" $predelete}}
      containers:
      - name: pre-delete-job
        image: {{ .Values.uninstaller.imageName }}{{ include "liqo.suffix" $predelete }}:{{ include "liqo.version" $predelete }}
        securityContext:
          {{- include "liqo.containerSecurityContext" . | nindent 10 }}
        command: ["/usr/bin/uninstaller"]
        {{- if or .Values.uninstaller.pod.extraArgs .Values.common.extraArgs }}
        args:
          {{- if .Values.common.extraArgs }}
          {{- toYaml .Values.common.extraArgs | nindent 10 }}
          {{- end }}
          {{- if .Values.uninstaller.pod.extraArgs }}
          {{- toYaml .Values.uninstaller.pod.extraArgs | nindent 10 }}
          {{- end }}
        {{- end }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources: {{- toYaml .Values.uninstaller.pod.resources | nindent 10 }}
      {{- if ((.Values.common).nodeSelector) }}
      nodeSelector:
      {{- toYaml .Values.common.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).tolerations) }}
      tolerations:
      {{- toYaml .Values.common.tolerations | nindent 8 }}
      {{- end }}
      {{- if ((.Values.common).affinity) }}
      affinity:
      {{- toYaml .Values.common.affinity | nindent 8 }}
      {{- end }}
