{{- $runtimeConfig := (merge (dict "name" "runtimeclass" "module" "runtimeclass") .) -}}

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  labels:
    {{- include "liqo.labels" $runtimeConfig | nindent 4 }}
    {{- with .Values.offloading.runtimeClass.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.offloading.runtimeClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.offloading.runtimeClass.name }}
handler: {{ .Values.offloading.runtimeClass.handler }}
scheduling:
  {{- if .Values.offloading.runtimeClass.nodeSelector.enabled }}
  nodeSelector:
    {{- toYaml .Values.offloading.runtimeClass.nodeSelector.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.offloading.runtimeClass.tolerations.enabled }}
  tolerations:
    {{- toYaml .Values.offloading.runtimeClass.tolerations.tolerations | nindent 4 }}
  {{- end }}
