---
{{- $netManagerConfig := (merge (dict "name" (required ".Values.networkManager.name" .Values.networkManager.name) "module" (required ".Values.networkManager.name is required" .Values.networkManager.module)) .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $netManagerConfig }}
  labels:
  {{- include "liqo.labels" $netManagerConfig | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $netManagerConfig | nindent 6 }}
  template:
    metadata:
    {{- if .Values.gateway.podAnnotations }}
      annotations:
        {{- toYaml .Values.gateway.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "liqo.labels" $netManagerConfig | nindent 8 }}
        {{- if .Values.gateway.podLabels }}
          {{- toYaml .Values.gateway.podLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $netManagerConfig }}
      containers:
        - image: {{ .Values.networkModule.tunnelEndpointOperator.image.repository }}{{ default .Values.suffix }}:{{ default .Values.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: tunnelendpointcreator-operator
          command: ["/usr/bin/liqonet"]
          args:
            - "-run-as=tunnelEndpointCreator-operator"
          resources:
            limits:
              cpu: 20m
              memory: 50M
            requests:
              cpu: 20m
              memory: 50M
