apiVersion: v1
kind: ConfigMap
metadata:
  name: liqo-dashboard-configmap
  namespace: {{ .Release.Namespace }}
data:
  oidc_client_id: ""
  oidc_provider_url: ""
  oidc_client_secret: ""
  oidc_redirect_uri: ""

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.agentConfig.appLabel }}
  name: liqo-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.agentConfig.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.agentConfig.appLabel }}
    spec:
      volumes:
        - name: shared-data
          emptyDir: { }
      initContainers:
        - name: proxy-cert
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /etc/nginx/ssl/
          command: [ "/bin/sh" ]
          args: [ "-c", 'openssl req -x509 -subj "/C=IT/ST=Turin/O=Liqo" -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.cert' ]
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.global.dashboard_version | default .Values.version }}
          volumeMounts:
            - name: shared-data
              mountPath: /etc/nginx/ssl/
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: liqo-dashboard
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: OIDC_PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  name: liqo-dashboard-configmap
                  key: oidc_provider_url
            - name: OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: liqo-dashboard-configmap
                  key: oidc_client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: liqo-dashboard-configmap
                  key: oidc_client_secret
            - name: OIDC_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: liqo-dashboard-configmap
                  key: oidc_redirect_uri

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.agentConfig.appLabel }}
  name: {{ .Values.agentConfig.service }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.agentConfig.appLabel }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.agentConfig.appLabel }}
  name: {{ .Values.agentConfig.serviceAccount }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.agentConfig.appLabel }}
  name: {{ .Values.agentConfig.serviceAccount }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.agentConfig.serviceAccount }}
  namespace: {{ .Release.Namespace }}

---

{{- if (.Values.global.dashboard_ingress)}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.agentConfig.appLabel }}
  name: {{ .Values.agentConfig.ingress }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.global.dashboard_ingress }}
      http:
        paths:
          - backend:
              serviceName: liqo-dashboard
              servicePort: 443
            path: /
  tls:
    - hosts:
        - {{ .Values.global.dashboard_ingress }}
      secretName: liqodash-tls-cert
{{- end }}