// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apisoffloadingv1beta1 "github.com/liqotech/liqo/apis/offloading/v1beta1"
	versioned "github.com/liqotech/liqo/pkg/client/clientset/versioned"
	internalinterfaces "github.com/liqotech/liqo/pkg/client/informers/externalversions/internalinterfaces"
	offloadingv1beta1 "github.com/liqotech/liqo/pkg/client/listers/offloading/v1beta1"
)

// ShadowRouteStatusInformer provides access to a shared informer and lister for
// ShadowRouteStatuses.
type ShadowRouteStatusInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() offloadingv1beta1.ShadowRouteStatusLister
}

type shadowRouteStatusInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewShadowRouteStatusInformer constructs a new informer for ShadowRouteStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewShadowRouteStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredShadowRouteStatusInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredShadowRouteStatusInformer constructs a new informer for ShadowRouteStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredShadowRouteStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowRouteStatuses(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowRouteStatuses(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowRouteStatuses(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowRouteStatuses(namespace).Watch(ctx, options)
			},
		}, client),
		&apisoffloadingv1beta1.ShadowRouteStatus{},
		resyncPeriod,
		indexers,
	)
}

func (f *shadowRouteStatusInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredShadowRouteStatusInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *shadowRouteStatusInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisoffloadingv1beta1.ShadowRouteStatus{}, f.defaultInformer)
}

func (f *shadowRouteStatusInformer) Lister() offloadingv1beta1.ShadowRouteStatusLister {
	return offloadingv1beta1.NewShadowRouteStatusLister(f.Informer().GetIndexer())
}
