// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apisoffloadingv1beta1 "github.com/liqotech/liqo/apis/offloading/v1beta1"
	versioned "github.com/liqotech/liqo/pkg/client/clientset/versioned"
	internalinterfaces "github.com/liqotech/liqo/pkg/client/informers/externalversions/internalinterfaces"
	offloadingv1beta1 "github.com/liqotech/liqo/pkg/client/listers/offloading/v1beta1"
)

// ShadowIngressStatusInformer provides access to a shared informer and lister for
// ShadowIngressStatuses.
type ShadowIngressStatusInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() offloadingv1beta1.ShadowIngressStatusLister
}

type shadowIngressStatusInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewShadowIngressStatusInformer constructs a new informer for ShadowIngressStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewShadowIngressStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredShadowIngressStatusInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredShadowIngressStatusInformer constructs a new informer for ShadowIngressStatus type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredShadowIngressStatusInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowIngressStatuses(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowIngressStatuses(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowIngressStatuses(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OffloadingV1beta1().ShadowIngressStatuses(namespace).Watch(ctx, options)
			},
		},
		&apisoffloadingv1beta1.ShadowIngressStatus{},
		resyncPeriod,
		indexers,
	)
}

func (f *shadowIngressStatusInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredShadowIngressStatusInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *shadowIngressStatusInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisoffloadingv1beta1.ShadowIngressStatus{}, f.defaultInformer)
}

func (f *shadowIngressStatusInformer) Lister() offloadingv1beta1.ShadowIngressStatusLister {
	return offloadingv1beta1.NewShadowIngressStatusLister(f.Informer().GetIndexer())
}
