# Default values for networkModule.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

routeOperator:
  image:
    repository: "liqo/liqonet"
    pullPolicy: "IfNotPresent"
tunnelEndpointOperator:
  image:
    repository: "liqo/liqonet"
    pullPolicy: "IfNotPresent"

suffix: ""
version: "latest"