version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/cert-creator"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/common"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/liqo-test"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/liqonet"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/build/proxy"
    schedule:
      interval: "daily"
