api:
  - api/**/* 

community:
  - AUTHORS
  - ./**/*/README.md
  - LICENSE
  - README.md

documentation:
  - docs/**/*

networking:
  - build/liqonet/**/*
  - cmd/liqonet/**/*
  - pkg/liqonet/**/*
  - internal/liqonet/**/*

virtual-node:
  - build/virtual-kubelet/**/*
  - build/init-vkubelet/**/*
  - cmd/virtual-kubelet/**/*
  - internal/kubernetes/**/*
  - internal/errdefs/**/*
  - internal/manager/**/*
  - internal/node/**/*
  - internal/trace/**/*
  - test/kubernetes_provider/**/*
  - build/pod-mutator/**/*

discovery:
  - internal/discovery/**/*
  - internal/peering-request-operator/**/*
  - build/peering-request-operator/**/*
  - build/discovery/**/*

advertisement_management:
  - build/advertisement-broadcaster/**/*
  - build/advertisement-operator/**/*
  - cmd/advertisement-operator/**/*
  - cmd/advertisement-broadcaster/**/*
  - internal/advertisement-operator/**/*
  - pkg/adevertisement-operator/**/*
  - test/unit/advertisement-operator

ui:
  - build/tray-agent/**/*
  - internal/tray-agent/**/*
  - cmd/tray-agent/**/*
