changelog:
  exclude:
    labels:
    - kind/no-changelog
    authors:
    - dependabot[bot]
  categories:
    - title: ":boom: Breaking Change"
      labels:
      - kind/breaking
    - title: ":rocket: New Features"
      labels:
      - kind/feature
    - title: ":bug: Bug Fixes"
      labels:
      - kind/bug
    - title: ":broom: Code Refactoring"
      labels:
      - kind/cleanup
    - title: ":memo: Documentation"
      labels:
      - kind/docs
    - title: Other Changes
      labels:
      - "*"
