version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    #- nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 300
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    goheader:
      values:
        const:
          AUTHORS: The Liqo Authors
      template: |-
        Copyright 2019-{{ YEAR }} {{ AUTHORS }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

             http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    gomodguard:
      blocked:
        modules:
          - github.com/go-logr/logr:
              recommendations:
                - k8s.io/klog/v2
    govet:
      enable:
        - shadow
        - nilness
        - nilfunc
    lll:
      line-length: 150
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - govet
        text: declaration of "(err|ctx)" shadows declaration at
      - linters:
          - gosec
        # Disable the check to test that HTTP clients are not using an insecure TLS connection.
        # We need it to contact the remote authentication services exposing a self-signed certificate
        text: TLS InsecureSkipVerify set true.
      - linters:
          - errorlint
        # Disable the check to test errors type assertion on switches.
        text: type switch on error will fail on wrapped errors. Use errors.As to check for specific errors
      - linters:
          - revive
          - whitespace
        path: _test\.go
      - path: (.+)\.go$
        # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    paths:
      - zz_generated.*.go
      - pkg/client
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
        sections:
        - standard                          # Captures all standard packages if they do not match another section.
        - default                           # Contains all imports that could not be matched to another section type.
        - prefix(github.com/liqotech/liqo)  # Groups all imports with the specified Prefix.
    goimports:
      local-prefixes:
        - github.com/liqotech/liqo
  exclusions:
    generated: lax
    paths:
      - zz_generated.*.go
      - pkg/client
      - third_party$
      - builtin$
      - examples$
