apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: test-liqo
spec:
  containers:
    - name: nginx
      image: nginxdemos/hello
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: web
  nodeSelector:
    type: virtual-node
---
apiVersion: v1
kind: Service
metadata:
  name: test-liqo
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web
  selector:
    app: test-liqo
  type: ClusterIP