---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatcher-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: dispatcher-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list

  - apiGroups:
      - liqonet.liqo.io
    resources:
      - networkconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - liqonet.liqo.io
    resources:
      - networkconfigs/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
    - discovery.liqo.io
    resources:
      - foreignclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.liqo.io
    resources:
      - foreignclusters/status
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - policy.liqo.io
    resources:
      - clusterconfigs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dispatcher-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dispatcher-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: dispatcher-operator-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dispatcher-operator
  name: dispatcher-operator
spec:
  selector:
    matchLabels:
      run: dispatcher-operator
  template:
    metadata:
      labels:
        run: dispatcher-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      serviceAccountName: dispatcher-operator-service-account
      containers:
        - image: {{ .Values.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: dispatcher-operator
          command: ["/usr/bin/dispatcher"]
          resources: {}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Always
