// Copyright 2019-2023 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	v1alpha1 "github.com/liqotech/liqo/apis/virtualkubelet/v1alpha1"
)

// ShadowEndpointSliceLister helps list ShadowEndpointSlices.
// All objects returned here must be treated as read-only.
type ShadowEndpointSliceLister interface {
	// List lists all ShadowEndpointSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ShadowEndpointSlice, err error)
	// ShadowEndpointSlices returns an object that can list and get ShadowEndpointSlices.
	ShadowEndpointSlices(namespace string) ShadowEndpointSliceNamespaceLister
	ShadowEndpointSliceListerExpansion
}

// shadowEndpointSliceLister implements the ShadowEndpointSliceLister interface.
type shadowEndpointSliceLister struct {
	indexer cache.Indexer
}

// NewShadowEndpointSliceLister returns a new ShadowEndpointSliceLister.
func NewShadowEndpointSliceLister(indexer cache.Indexer) ShadowEndpointSliceLister {
	return &shadowEndpointSliceLister{indexer: indexer}
}

// List lists all ShadowEndpointSlices in the indexer.
func (s *shadowEndpointSliceLister) List(selector labels.Selector) (ret []*v1alpha1.ShadowEndpointSlice, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ShadowEndpointSlice))
	})
	return ret, err
}

// ShadowEndpointSlices returns an object that can list and get ShadowEndpointSlices.
func (s *shadowEndpointSliceLister) ShadowEndpointSlices(namespace string) ShadowEndpointSliceNamespaceLister {
	return shadowEndpointSliceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ShadowEndpointSliceNamespaceLister helps list and get ShadowEndpointSlices.
// All objects returned here must be treated as read-only.
type ShadowEndpointSliceNamespaceLister interface {
	// List lists all ShadowEndpointSlices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ShadowEndpointSlice, err error)
	// Get retrieves the ShadowEndpointSlice from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ShadowEndpointSlice, error)
	ShadowEndpointSliceNamespaceListerExpansion
}

// shadowEndpointSliceNamespaceLister implements the ShadowEndpointSliceNamespaceLister
// interface.
type shadowEndpointSliceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ShadowEndpointSlices in the indexer for a given namespace.
func (s shadowEndpointSliceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ShadowEndpointSlice, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ShadowEndpointSlice))
	})
	return ret, err
}

// Get retrieves the ShadowEndpointSlice from the indexer for a given namespace and name.
func (s shadowEndpointSliceNamespaceLister) Get(name string) (*v1alpha1.ShadowEndpointSlice, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("shadowendpointslice"), name)
	}
	return obj.(*v1alpha1.ShadowEndpointSlice), nil
}
