// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	v1alpha1 "github.com/liqotech/liqo/apis/ipam/v1alpha1"
	ipamv1alpha1 "github.com/liqotech/liqo/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
)

// fakeIPs implements IPInterface
type fakeIPs struct {
	*gentype.FakeClientWithList[*v1alpha1.IP, *v1alpha1.IPList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPs(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.IPInterface {
	return &fakeIPs{
		gentype.NewFakeClientWithList[*v1alpha1.IP, *v1alpha1.IPList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ips"),
			v1alpha1.SchemeGroupVersion.WithKind("IP"),
			func() *v1alpha1.IP { return &v1alpha1.IP{} },
			func() *v1alpha1.IPList { return &v1alpha1.IPList{} },
			func(dst, src *v1alpha1.IPList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPList) []*v1alpha1.IP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPList, items []*v1alpha1.IP) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
