{{- $cfg := (merge (dict "name" "webhook-certificate-patch" "module" "webhook-certificate-patch") .) -}}
{{- $webhookConfig := (merge (dict "name" "webhook" "module" "webhook") .) -}}
{{- $ctrlManagerConfig := (merge (dict "name" "controller-manager" "module" "controller-manager") .) -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "liqo.prefixedName" $cfg }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "liqo.labels" $cfg | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name:  {{ include "liqo.prefixedName" $cfg }}
      labels:
        {{- include "liqo.labels" $cfg | nindent 8 }}
    spec:
      containers:
      - name: create
        image: {{ .Values.webhook.patch.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        args:
        - create
        - --host={{ include "liqo.prefixedName" $ctrlManagerConfig }},{{ include "liqo.prefixedName" $ctrlManagerConfig }}.{{ .Release.Namespace }},{{ include "liqo.prefixedName" $ctrlManagerConfig }}.{{ .Release.Namespace }}.svc,{{ include "liqo.prefixedName" $ctrlManagerConfig }}.{{ .Release.Namespace }}.svc.cluster.local
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{ include "liqo.prefixedName" $webhookConfig }}-certs
        - --cert-name=tls.crt
        - --key-name=tls.key
        securityContext:
          {{- include "liqo.containerSecurityContext" . | nindent 10 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "liqo.prefixedName" $cfg }}
      securityContext:
        {{- include "liqo.podSecurityContext" . | nindent 8 }}
