// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"

	v1beta1 "github.com/liqotech/liqo/apis/networking/v1beta1"
)

// IPSpecApplyConfiguration represents a declarative configuration of the IPSpec type for use
// with apply.
//
// IPSpec defines a local IP.
type IPSpecApplyConfiguration struct {
	// IP is the local IP.
	IP *v1beta1.IP `json:"ip,omitempty"`
	// NetworkRef is the reference to the Network CR containing the CIDR where the desired IP should be allocated from.
	// It is optional, if left empty the IP will be allocated in a default network CIDR (e.g., external CIDR).
	NetworkRef *v1.ObjectReference `json:"networkRef,omitempty"`
	// ServiceTemplate contains the template to create the associated service (and endpointslice) for the IP endopoint.
	// If empty the creation of the service is disabled (default).
	ServiceTemplate *ServiceTemplateApplyConfiguration `json:"serviceTemplate,omitempty"`
	// Masquerade is a flag to enable masquerade for the local IP on nodes.
	// If empty the masquerade is disabled.
	Masquerade *bool `json:"masquerade,omitempty"`
}

// IPSpecApplyConfiguration constructs a declarative configuration of the IPSpec type for use with
// apply.
func IPSpec() *IPSpecApplyConfiguration {
	return &IPSpecApplyConfiguration{}
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *IPSpecApplyConfiguration) WithIP(value v1beta1.IP) *IPSpecApplyConfiguration {
	b.IP = &value
	return b
}

// WithNetworkRef sets the NetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkRef field is set to the value of the last call.
func (b *IPSpecApplyConfiguration) WithNetworkRef(value v1.ObjectReference) *IPSpecApplyConfiguration {
	b.NetworkRef = &value
	return b
}

// WithServiceTemplate sets the ServiceTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceTemplate field is set to the value of the last call.
func (b *IPSpecApplyConfiguration) WithServiceTemplate(value *ServiceTemplateApplyConfiguration) *IPSpecApplyConfiguration {
	b.ServiceTemplate = value
	return b
}

// WithMasquerade sets the Masquerade field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Masquerade field is set to the value of the last call.
func (b *IPSpecApplyConfiguration) WithMasquerade(value bool) *IPSpecApplyConfiguration {
	b.Masquerade = &value
	return b
}
