// Copyright 2019-2025 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// NamespaceMapListerExpansion allows custom methods to be added to
// NamespaceMapLister.
type NamespaceMapListerExpansion interface{}

// NamespaceMapNamespaceListerExpansion allows custom methods to be added to
// NamespaceMapNamespaceLister.
type NamespaceMapNamespaceListerExpansion interface{}

// ShadowEndpointSliceListerExpansion allows custom methods to be added to
// ShadowEndpointSliceLister.
type ShadowEndpointSliceListerExpansion interface{}

// ShadowEndpointSliceNamespaceListerExpansion allows custom methods to be added to
// ShadowEndpointSliceNamespaceLister.
type ShadowEndpointSliceNamespaceListerExpansion interface{}

// ShadowPodListerExpansion allows custom methods to be added to
// ShadowPodLister.
type ShadowPodListerExpansion interface{}

// ShadowPodNamespaceListerExpansion allows custom methods to be added to
// ShadowPodNamespaceLister.
type ShadowPodNamespaceListerExpansion interface{}

// VirtualNodeListerExpansion allows custom methods to be added to
// VirtualNodeLister.
type VirtualNodeListerExpansion interface{}

// VirtualNodeNamespaceListerExpansion allows custom methods to be added to
// VirtualNodeNamespaceLister.
type VirtualNodeNamespaceListerExpansion interface{}

// VkOptionsTemplateListerExpansion allows custom methods to be added to
// VkOptionsTemplateLister.
type VkOptionsTemplateListerExpansion interface{}

// VkOptionsTemplateNamespaceListerExpansion allows custom methods to be added to
// VkOptionsTemplateNamespaceLister.
type VkOptionsTemplateNamespaceListerExpansion interface{}
