// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	v1beta1 "github.com/liqotech/liqo/apis/offloading/v1beta1"
	offloadingv1beta1 "github.com/liqotech/liqo/pkg/client/clientset/versioned/typed/offloading/v1beta1"
)

// fakeShadowIngressStatuses implements ShadowIngressStatusInterface
type fakeShadowIngressStatuses struct {
	*gentype.FakeClientWithList[*v1beta1.ShadowIngressStatus, *v1beta1.ShadowIngressStatusList]
	Fake *FakeOffloadingV1beta1
}

func newFakeShadowIngressStatuses(fake *FakeOffloadingV1beta1, namespace string) offloadingv1beta1.ShadowIngressStatusInterface {
	return &fakeShadowIngressStatuses{
		gentype.NewFakeClientWithList[*v1beta1.ShadowIngressStatus, *v1beta1.ShadowIngressStatusList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("shadowingressstatuses"),
			v1beta1.SchemeGroupVersion.WithKind("ShadowIngressStatus"),
			func() *v1beta1.ShadowIngressStatus { return &v1beta1.ShadowIngressStatus{} },
			func() *v1beta1.ShadowIngressStatusList { return &v1beta1.ShadowIngressStatusList{} },
			func(dst, src *v1beta1.ShadowIngressStatusList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ShadowIngressStatusList) []*v1beta1.ShadowIngressStatus {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.ShadowIngressStatusList, items []*v1beta1.ShadowIngressStatus) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
