// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	v1beta1 "github.com/liqotech/liqo/apis/offloading/v1beta1"
	offloadingv1beta1 "github.com/liqotech/liqo/pkg/client/clientset/versioned/typed/offloading/v1beta1"
)

// fakeShadowEndpointSlices implements ShadowEndpointSliceInterface
type fakeShadowEndpointSlices struct {
	*gentype.FakeClientWithList[*v1beta1.ShadowEndpointSlice, *v1beta1.ShadowEndpointSliceList]
	Fake *FakeOffloadingV1beta1
}

func newFakeShadowEndpointSlices(fake *FakeOffloadingV1beta1, namespace string) offloadingv1beta1.ShadowEndpointSliceInterface {
	return &fakeShadowEndpointSlices{
		gentype.NewFakeClientWithList[*v1beta1.ShadowEndpointSlice, *v1beta1.ShadowEndpointSliceList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("shadowendpointslices"),
			v1beta1.SchemeGroupVersion.WithKind("ShadowEndpointSlice"),
			func() *v1beta1.ShadowEndpointSlice { return &v1beta1.ShadowEndpointSlice{} },
			func() *v1beta1.ShadowEndpointSliceList { return &v1beta1.ShadowEndpointSliceList{} },
			func(dst, src *v1beta1.ShadowEndpointSliceList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.ShadowEndpointSliceList) []*v1beta1.ShadowEndpointSlice {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.ShadowEndpointSliceList, items []*v1beta1.ShadowEndpointSlice) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
