{{- $ctrlManagerConfig := (merge (dict "name" "controller-manager" "module" "controller-manager") .) -}}
{{- $webhookConfig := (merge (dict "name" "webhook" "module" "webhook") .) -}}

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "liqo.prefixedName" $webhookConfig }}
  labels:
    {{- include "liqo.labels" $webhookConfig | nindent 4 }}
webhooks:
  - name: fc.validate.liqo.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
        namespace: {{ .Release.Namespace }}
        path: "/validate/foreign-cluster"
        port: {{ .Values.webhook.port }}
    rules:
      - operations: ["UPDATE"]
        apiGroups: ["discovery.liqo.io"]
        apiVersions: ["v1alpha1"]
        resources: ["foreignclusters"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
  - name: nsoff.validate.liqo.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
        namespace: {{ .Release.Namespace }}
        path: "/validate/namespace-offloading"
        port: {{ .Values.webhook.port }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["offloading.liqo.io"]
        apiVersions: ["v1alpha1"]
        resources: ["namespaceoffloadings"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
  - name: shadowpod.validate.liqo.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ include "liqo.prefixedName" $ctrlManagerConfig }}
        namespace: {{ .Release.Namespace }}
        path: "/validate/shadowpods"
        port: {{ .Values.webhook.port }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["virtualkubelet.liqo.io"]
        apiVersions: ["v1alpha1"]
        resources: ["shadowpods"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
