{
 "title": "Liqo Virtual-Kubelet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "prometheus" },
   {
    "name": "clusterName",
    "query": {
     "query": "label_values(liqo_virtual_kubelet_reflection_item_counter, cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(liqo_virtual_kubelet_reflection_item_counter, exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Virtual-kubelet:$clusterName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "clusterName" },
  {
   "title": "Total resources reflected",
   "type": "stat",
   "description": "The total number of items successfully reflected.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by(resource_type) (liqo_virtual_kubelet_reflection_item_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reflected resources and transient errors",
   "type": "timeseries",
   "description": "This graph represents a per-second overview of reflected items and transient errors.",
   "gridPos": { "h": 6, "w": 20, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(sum(increase(liqo_virtual_kubelet_reflection_item_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}[$__rate_interval])), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(liqo_virtual_kubelet_reflection_error_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total transient errors",
   "type": "stat",
   "description": "The total number of transient errors.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by(resource_type) (liqo_virtual_kubelet_reflection_error_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reflected resources",
   "type": "stat",
   "description": "The number of items successfully reflected for each resource.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by(reflector_resource) (liqo_virtual_kubelet_reflection_item_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of reflected resources",
   "type": "timeseries",
   "description": "The representation of all resources successfully reflected in the interval range specified.",
   "gridPos": { "h": 6, "w": 20, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "label_replace(sum by(reflector_resource) (increase(liqo_virtual_kubelet_reflection_item_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}[$__rate_interval])), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource errors",
   "type": "stat",
   "description": "The number of each resource that caused a transient error.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(sum by(reflector_resource) (liqo_virtual_kubelet_reflection_error_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transient errors for resource type",
   "type": "timeseries",
   "description": "The representation of resources which caused a transient error in the interval range specified.",
   "gridPos": { "h": 6, "w": 20, "x": 3, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(sum by(reflector_resource) (increase(liqo_virtual_kubelet_reflection_error_counter{cluster_name=\"$clusterName\", exported_namespace=~\"^$namespace\"}[$__rate_interval])), \"pod\", \"\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}