// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/discovery/v1"
)

// EndpointSliceTemplateApplyConfiguration represents a declarative configuration of the EndpointSliceTemplate type for use
// with apply.
//
// EndpointSliceTemplate defines the desired state of the EndpointSlice.
type EndpointSliceTemplateApplyConfiguration struct {
	Endpoints   []v1.Endpoint     `json:"endpoints,omitempty"`
	Ports       []v1.EndpointPort `json:"ports,omitempty"`
	AddressType *v1.AddressType   `json:"addressType,omitempty"`
}

// EndpointSliceTemplateApplyConfiguration constructs a declarative configuration of the EndpointSliceTemplate type for use with
// apply.
func EndpointSliceTemplate() *EndpointSliceTemplateApplyConfiguration {
	return &EndpointSliceTemplateApplyConfiguration{}
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *EndpointSliceTemplateApplyConfiguration) WithEndpoints(values ...v1.Endpoint) *EndpointSliceTemplateApplyConfiguration {
	for i := range values {
		b.Endpoints = append(b.Endpoints, values[i])
	}
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *EndpointSliceTemplateApplyConfiguration) WithPorts(values ...v1.EndpointPort) *EndpointSliceTemplateApplyConfiguration {
	for i := range values {
		b.Ports = append(b.Ports, values[i])
	}
	return b
}

// WithAddressType sets the AddressType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AddressType field is set to the value of the last call.
func (b *EndpointSliceTemplateApplyConfiguration) WithAddressType(value v1.AddressType) *EndpointSliceTemplateApplyConfiguration {
	b.AddressType = &value
	return b
}
