// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// NamespaceMapSpecApplyConfiguration represents a declarative configuration of the NamespaceMapSpec type for use
// with apply.
//
// NamespaceMapSpec defines the desired state of NamespaceMap.
type NamespaceMapSpecApplyConfiguration struct {
	// DesiredMapping is filled by NamespaceController when a user requires to offload a remote namespace, every entry
	// of the map represents the localNamespaceName[key]-remoteNamespaceName[value] association. When a new entry is
	// created the NamespaceMap Controller tries to create the associated remote namespace.
	DesiredMapping map[string]string `json:"desiredMapping,omitempty"`
}

// NamespaceMapSpecApplyConfiguration constructs a declarative configuration of the NamespaceMapSpec type for use with
// apply.
func NamespaceMapSpec() *NamespaceMapSpecApplyConfiguration {
	return &NamespaceMapSpecApplyConfiguration{}
}

// WithDesiredMapping puts the entries into the DesiredMapping field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the DesiredMapping field,
// overwriting an existing map entries in DesiredMapping field with the same key.
func (b *NamespaceMapSpecApplyConfiguration) WithDesiredMapping(entries map[string]string) *NamespaceMapSpecApplyConfiguration {
	if b.DesiredMapping == nil && len(entries) > 0 {
		b.DesiredMapping = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.DesiredMapping[k] = v
	}
	return b
}
