// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// OffloadingPatchApplyConfiguration represents a declarative configuration of the OffloadingPatch type for use
// with apply.
//
// OffloadingPatch contains the information to patch the virtual node.
type OffloadingPatchApplyConfiguration struct {
	// AnnotationsNotReflected is the list of annotations (key) that must not be reflected
	AnnotationsNotReflected []string `json:"annotationsNotReflected,omitempty"`
	// LabelsNotReflected is the list of labels (key) that must not be reflected
	LabelsNotReflected []string `json:"labelsNotReflected,omitempty"`
	// NodeSelector contains the node selector to target the remote cluster.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// Tolerations contains the tolerations to target the remote cluster.
	Tolerations []v1.Toleration `json:"tolerations,omitempty"`
	// Affinity contains the affinity and anti-affinity rules to target the remote cluster.
	Affinity *AffinityApplyConfiguration `json:"affinity,omitempty"`
	// RuntimeClassName contains the runtimeclass name the pods should have on the target remote cluster.
	RuntimeClassName *string `json:"runtimeClassName,omitempty"`
}

// OffloadingPatchApplyConfiguration constructs a declarative configuration of the OffloadingPatch type for use with
// apply.
func OffloadingPatch() *OffloadingPatchApplyConfiguration {
	return &OffloadingPatchApplyConfiguration{}
}

// WithAnnotationsNotReflected adds the given value to the AnnotationsNotReflected field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AnnotationsNotReflected field.
func (b *OffloadingPatchApplyConfiguration) WithAnnotationsNotReflected(values ...string) *OffloadingPatchApplyConfiguration {
	for i := range values {
		b.AnnotationsNotReflected = append(b.AnnotationsNotReflected, values[i])
	}
	return b
}

// WithLabelsNotReflected adds the given value to the LabelsNotReflected field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LabelsNotReflected field.
func (b *OffloadingPatchApplyConfiguration) WithLabelsNotReflected(values ...string) *OffloadingPatchApplyConfiguration {
	for i := range values {
		b.LabelsNotReflected = append(b.LabelsNotReflected, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *OffloadingPatchApplyConfiguration) WithNodeSelector(entries map[string]string) *OffloadingPatchApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *OffloadingPatchApplyConfiguration) WithTolerations(values ...v1.Toleration) *OffloadingPatchApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *OffloadingPatchApplyConfiguration) WithAffinity(value *AffinityApplyConfiguration) *OffloadingPatchApplyConfiguration {
	b.Affinity = value
	return b
}

// WithRuntimeClassName sets the RuntimeClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeClassName field is set to the value of the last call.
func (b *OffloadingPatchApplyConfiguration) WithRuntimeClassName(value string) *OffloadingPatchApplyConfiguration {
	b.RuntimeClassName = &value
	return b
}
