// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	offloadingv1beta1 "github.com/liqotech/liqo/apis/offloading/v1beta1"
)

// RemoteNamespaceStatusApplyConfiguration represents a declarative configuration of the RemoteNamespaceStatus type for use
// with apply.
//
// RemoteNamespaceStatus contains some information about remote namespace status.
type RemoteNamespaceStatusApplyConfiguration struct {
	// RemoteNamespace is the name chosen by the user at creation time according to NamespaceMappingStrategy
	RemoteNamespace *string `json:"remoteNamespace,omitempty"`
	// Phase is the remote Namespace's actual status (Accepted,Refused).
	Phase *offloadingv1beta1.MappingPhase `json:"phase,omitempty"`
}

// RemoteNamespaceStatusApplyConfiguration constructs a declarative configuration of the RemoteNamespaceStatus type for use with
// apply.
func RemoteNamespaceStatus() *RemoteNamespaceStatusApplyConfiguration {
	return &RemoteNamespaceStatusApplyConfiguration{}
}

// WithRemoteNamespace sets the RemoteNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteNamespace field is set to the value of the last call.
func (b *RemoteNamespaceStatusApplyConfiguration) WithRemoteNamespace(value string) *RemoteNamespaceStatusApplyConfiguration {
	b.RemoteNamespace = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *RemoteNamespaceStatusApplyConfiguration) WithPhase(value offloadingv1beta1.MappingPhase) *RemoteNamespaceStatusApplyConfiguration {
	b.Phase = &value
	return b
}
