// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/networking/v1"
)

// ShadowIngressStatusSpecApplyConfiguration represents a declarative configuration of the ShadowIngressStatusSpec type for use
// with apply.
//
// ShadowIngressStatusSpec defines the desired state of ShadowIngressStatus.
type ShadowIngressStatusSpecApplyConfiguration struct {
	// IngressName is the name of the local Ingress whose remote status is reported.
	IngressName *string `json:"ingressName,omitempty"`
	// ClusterID is the ID of the remote cluster that owns this status.
	ClusterID *string `json:"clusterID,omitempty"`
	// LoadBalancer is the load-balancer status of the remote Ingress.
	LoadBalancer *v1.IngressLoadBalancerStatus `json:"loadBalancer,omitempty"`
}

// ShadowIngressStatusSpecApplyConfiguration constructs a declarative configuration of the ShadowIngressStatusSpec type for use with
// apply.
func ShadowIngressStatusSpec() *ShadowIngressStatusSpecApplyConfiguration {
	return &ShadowIngressStatusSpecApplyConfiguration{}
}

// WithIngressName sets the IngressName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IngressName field is set to the value of the last call.
func (b *ShadowIngressStatusSpecApplyConfiguration) WithIngressName(value string) *ShadowIngressStatusSpecApplyConfiguration {
	b.IngressName = &value
	return b
}

// WithClusterID sets the ClusterID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterID field is set to the value of the last call.
func (b *ShadowIngressStatusSpecApplyConfiguration) WithClusterID(value string) *ShadowIngressStatusSpecApplyConfiguration {
	b.ClusterID = &value
	return b
}

// WithLoadBalancer sets the LoadBalancer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancer field is set to the value of the last call.
func (b *ShadowIngressStatusSpecApplyConfiguration) WithLoadBalancer(value v1.IngressLoadBalancerStatus) *ShadowIngressStatusSpecApplyConfiguration {
	b.LoadBalancer = &value
	return b
}
