// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// VkOptionsTemplateSpecApplyConfiguration represents a declarative configuration of the VkOptionsTemplateSpec type for use
// with apply.
//
// VkOptionsTemplateSpec defines the desired state of VkOptionsTemplate.
type VkOptionsTemplateSpecApplyConfiguration struct {
	CreateNode              *bool                                        `json:"createNode,omitempty"`
	DisableNetworkCheck     *bool                                        `json:"disableNetworkCheck,omitempty"`
	ContainerImage          *string                                      `json:"containerImage,omitempty"`
	MetricsEnabled          *bool                                        `json:"metricsEnabled,omitempty"`
	MetricsAddress          *string                                      `json:"metricsAddress,omitempty"`
	LabelsNotReflected      []string                                     `json:"labelsNotReflected,omitempty"`
	AnnotationsNotReflected []string                                     `json:"annotationsNotReflected,omitempty"`
	ReflectorsConfig        map[string]ReflectorConfigApplyConfiguration `json:"reflectorsConfig,omitempty"`
	Resources               *v1.ResourceRequirements                     `json:"resources,omitempty"`
	ExtraArgs               []string                                     `json:"extraArgs,omitempty"`
	ExtraAnnotations        map[string]string                            `json:"extraAnnotations,omitempty"`
	ExtraLabels             map[string]string                            `json:"extraLabels,omitempty"`
	NodeExtraAnnotations    map[string]string                            `json:"nodeExtraAnnotations,omitempty"`
	NodeExtraLabels         map[string]string                            `json:"nodeExtraLabels,omitempty"`
	Replicas                *int32                                       `json:"replicas,omitempty"`
	ImagePullSecrets        []v1.LocalObjectReference                    `json:"imagePullSecrets,omitempty"`
	PullPolicy              *v1.PullPolicy                               `json:"pullPolicy,omitempty"`
	Tolerations             []v1.Toleration                              `json:"tolerations,omitempty"`
}

// VkOptionsTemplateSpecApplyConfiguration constructs a declarative configuration of the VkOptionsTemplateSpec type for use with
// apply.
func VkOptionsTemplateSpec() *VkOptionsTemplateSpecApplyConfiguration {
	return &VkOptionsTemplateSpecApplyConfiguration{}
}

// WithCreateNode sets the CreateNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateNode field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithCreateNode(value bool) *VkOptionsTemplateSpecApplyConfiguration {
	b.CreateNode = &value
	return b
}

// WithDisableNetworkCheck sets the DisableNetworkCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableNetworkCheck field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithDisableNetworkCheck(value bool) *VkOptionsTemplateSpecApplyConfiguration {
	b.DisableNetworkCheck = &value
	return b
}

// WithContainerImage sets the ContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerImage field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithContainerImage(value string) *VkOptionsTemplateSpecApplyConfiguration {
	b.ContainerImage = &value
	return b
}

// WithMetricsEnabled sets the MetricsEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsEnabled field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithMetricsEnabled(value bool) *VkOptionsTemplateSpecApplyConfiguration {
	b.MetricsEnabled = &value
	return b
}

// WithMetricsAddress sets the MetricsAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsAddress field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithMetricsAddress(value string) *VkOptionsTemplateSpecApplyConfiguration {
	b.MetricsAddress = &value
	return b
}

// WithLabelsNotReflected adds the given value to the LabelsNotReflected field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LabelsNotReflected field.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithLabelsNotReflected(values ...string) *VkOptionsTemplateSpecApplyConfiguration {
	for i := range values {
		b.LabelsNotReflected = append(b.LabelsNotReflected, values[i])
	}
	return b
}

// WithAnnotationsNotReflected adds the given value to the AnnotationsNotReflected field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AnnotationsNotReflected field.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithAnnotationsNotReflected(values ...string) *VkOptionsTemplateSpecApplyConfiguration {
	for i := range values {
		b.AnnotationsNotReflected = append(b.AnnotationsNotReflected, values[i])
	}
	return b
}

// WithReflectorsConfig puts the entries into the ReflectorsConfig field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ReflectorsConfig field,
// overwriting an existing map entries in ReflectorsConfig field with the same key.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithReflectorsConfig(entries map[string]ReflectorConfigApplyConfiguration) *VkOptionsTemplateSpecApplyConfiguration {
	if b.ReflectorsConfig == nil && len(entries) > 0 {
		b.ReflectorsConfig = make(map[string]ReflectorConfigApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.ReflectorsConfig[k] = v
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *VkOptionsTemplateSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithExtraArgs adds the given value to the ExtraArgs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraArgs field.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithExtraArgs(values ...string) *VkOptionsTemplateSpecApplyConfiguration {
	for i := range values {
		b.ExtraArgs = append(b.ExtraArgs, values[i])
	}
	return b
}

// WithExtraAnnotations puts the entries into the ExtraAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraAnnotations field,
// overwriting an existing map entries in ExtraAnnotations field with the same key.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithExtraAnnotations(entries map[string]string) *VkOptionsTemplateSpecApplyConfiguration {
	if b.ExtraAnnotations == nil && len(entries) > 0 {
		b.ExtraAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraAnnotations[k] = v
	}
	return b
}

// WithExtraLabels puts the entries into the ExtraLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraLabels field,
// overwriting an existing map entries in ExtraLabels field with the same key.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithExtraLabels(entries map[string]string) *VkOptionsTemplateSpecApplyConfiguration {
	if b.ExtraLabels == nil && len(entries) > 0 {
		b.ExtraLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraLabels[k] = v
	}
	return b
}

// WithNodeExtraAnnotations puts the entries into the NodeExtraAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeExtraAnnotations field,
// overwriting an existing map entries in NodeExtraAnnotations field with the same key.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithNodeExtraAnnotations(entries map[string]string) *VkOptionsTemplateSpecApplyConfiguration {
	if b.NodeExtraAnnotations == nil && len(entries) > 0 {
		b.NodeExtraAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeExtraAnnotations[k] = v
	}
	return b
}

// WithNodeExtraLabels puts the entries into the NodeExtraLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeExtraLabels field,
// overwriting an existing map entries in NodeExtraLabels field with the same key.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithNodeExtraLabels(entries map[string]string) *VkOptionsTemplateSpecApplyConfiguration {
	if b.NodeExtraLabels == nil && len(entries) > 0 {
		b.NodeExtraLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeExtraLabels[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithReplicas(value int32) *VkOptionsTemplateSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *VkOptionsTemplateSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithPullPolicy sets the PullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullPolicy field is set to the value of the last call.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithPullPolicy(value v1.PullPolicy) *VkOptionsTemplateSpecApplyConfiguration {
	b.PullPolicy = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *VkOptionsTemplateSpecApplyConfiguration) WithTolerations(values ...v1.Toleration) *VkOptionsTemplateSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}
