name: Feature Proposal 🚀
description: Suggest a feature to Liqo
labels: ["feature proposal"]
body:
- type: textarea
  attributes:
    label: Describe the problem you are having (if any)
    description: Explain which is the problem you would like to address with this feature proposal
    placeholder: A clear description of the problem that you are having, either because of your specific requirements/use cases, or because of a limitation of Liqo.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you would like
    description: Include any specific requirement you need
    placeholder: A clear description of what you would like to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the user value of this feature
    description: Explain how this feature will benefit the users.
    placeholder: A clear description of the user value.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
    description: Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach within the Liqo community before spending time implementing a change.
    placeholder: A clear description of how you would like to implement it. Please consider to ask for a slot in one of the upcoming community meetings as described in [COMMUNITY-HOW-TO.md](https://github.com/liqotech/liqo-community/blob/main/COMMUNITY-HOW-TO.md).
  validations:
    required: false
- type: checkboxes
  id: implement
  attributes:
    label: Do you volunteer to implement this feature?
    description: If you are willing to implement this feature, please check the box below. 
    options:
      - label: I want to implement this feature
        required: false
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/liqotech/liqo/blob/master/CODE_OF_CONDUCT.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
