---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: peering-request-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: peering-request-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: peering-request-operator
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: peering-request-operator
  template:
    metadata:
      labels:
        run: peering-request-operator
    spec:
      serviceAccountName: peering-request-operator
      containers:
        - image: liqo/peering-request-operator
          name: peering-request-operator
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          args:
            - "--cert-path"
            - "/etc/webhook/certs"
            - "--namespace"
            - "$(POD_NAMESPACE)"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: peering-request-operator
  namespace: {{ .Release.Namespace }}
  labels:
    run: peering-request-operator
spec:
  type: ClusterIP
  selector:
    run: peering-request-operator
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
