apiVersion: policy.liqo.io/v1
kind: ClusterConfig
metadata:
  name: configuration
  labels:
    app: liqo.io
spec:
  advertisementConfig:
    autoAccept: true
    maxAcceptableAdvertisement: 5
    resourceSharingPercentage: 30
  discoveryConfig:
    autojoin: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    service: _liqo._tcp
    updateTime: 3
    waitTime: 2
    dnsServer: '8.8.8.8:53'
  liqonetConfig:
    gatewayPrivateIP: {{ .Values.gatewayPrivateIP }}
    reservedSubnets:
    - {{ .Values.podCIDR }}
    - {{ .Values.serviceCIDR }}
