apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configmapName }}
  labels:
    app: liqo.io
data:
  clusterID: {{ .Values.clusterID}}
  podCIDR: {{ .Values.podCIDR}}
  serviceCIDR: {{ .Values.serviceCIDR}}
  gatewayPrivateIP: {{ .Values.gatewayPrivateIP}}
  gatewayIP: {{ .Values.gatewayIP}}