---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-sa
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liqo-discovery
rules:
  - apiGroups:
      - discovery.liqo.io
    resources:
      - foreignclusters
      - searchdomains
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create
      - delete
  - apiGroups:
      - discovery.liqo.io
    resources:
      - peeringrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.liqo.io
    resources:
      - clusterconfigs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - net.liqo.io
    resources:
      - networkconfigs
      - tunnelendpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - sharing.liqo.io
    resources:
      - advertisements
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - get
      - create

  # to satisfy ClusterRoles creation
  - apiGroups:
      - ""
      - sharing.liqo.io
    resources:
      - advertisements
      - advertisements/status
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - apiGroups:
      - net.liqo.io
    resources:
      - networkconfigs
      - networkconfigs/status
    verbs:
      - "*"
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachines/status
    verbs:
      - "*"
  - apiGroups:
      - acid.zalan.do
    resources:
      - postgresqls
      - postgresqls/status
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liqo-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discovery
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
subjects:
  - kind: ServiceAccount
    name: discovery-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: liqo-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
subjects:
  - kind: ServiceAccount
    name: discovery-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: discovery
    app: liqo.io
  name: discovery
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: discovery
  template:
    metadata:
      labels:
        run: discovery
    spec:
      serviceAccountName: discovery-sa
      containers:
        - image: {{ .Values.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          name: discovery
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/entrypoint.sh", "/usr/bin/discovery"]
          args:
          - "--namespace"
          - "$(POD_NAMESPACE)"
          - "--requeueAfter"
          - "30"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{ if .Values.apiServerIp }}
            - name: APISERVER
              value: {{ .Values.apiServerIp }}
            {{ end }}
            {{ if .Values.apiServerPort }}
            - name: APISERVER_PORT
              value: {{ .Values.apiServerPort }}
            {{ end }}
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates
              name: ca-certificates
          resources:
            limits:
              cpu: 50m
              memory: 50M
            requests:
              cpu: 50m
              memory: 50M
      volumes:
        - name: ca-certificates
          configMap:
            name: trusted-ca-certificates
      hostNetwork: true

