apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-role-peering
  labels:
    k8s-app: discovery
    app: liqo.io
rules:
  - apiGroups: ["discovery.liqo.io"]
    resources: ["peeringrequests"]
    verbs: ["get", "create", "delete", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-role-secret
  labels:
    k8s-app: discovery
    app: liqo.io
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-role-secret-ca
  labels:
    k8s-app: discovery
    app: liqo.io
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["ca-data"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-binding-peering
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-role-peering
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anonymous-binding-secret
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-role-secret
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anonymous-binding-secret-ca
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-role-secret-ca
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous
