# Default values for discoveryOperator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  repository: "liqo/discovery"
  pullPolicy: "IfNotPresent"

suffix: ""
version: "latest"
