---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: advertisement-operator
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: advertisement-operator
    app: liqo.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liqo-advertisement-operator-crd-role
rules:
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/legacy-unknown
    verbs:
      - approve
  - apiGroups:
      - discovery.liqo.io
    resources:
      - foreignclusters
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sharing.liqo.io
    resources:
      - advertisements
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - net.liqo.io
    resources:
      - advertisement/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - config.liqo.io
    resources:
      - clusterconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liqo-advertisement-operator-vk-role
rules:
- apiGroups:
    - ""
  resources:
    - deployments
    - configmaps
    - secrets
    - serviceaccounts
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: advertisement-operator
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: advertisement-operator
    app: liqo.io
subjects:
  - kind: ServiceAccount
    name: advertisement-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-advertisement-operator-vk-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: advertisement-operator
  labels:
    k8s-app: advertisement-operator
    app: liqo.io
subjects:
  - kind: ServiceAccount
    name: advertisement-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-advertisement-operator-crd-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    run: advertisement-operator
    app: liqo.io
  name: advertisement-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: advertisement-operator
  template:
    metadata:
      labels:
        run: advertisement-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      serviceAccountName: advertisement-operator
      containers:
      - image: {{ .Values.advController.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
        imagePullPolicy: {{ .Values.advController.image.pullPolicy }}
        name: advertisement-operator
        command: ["/usr/bin/advertisement-operator"]
        args:
          - "--cluster-id"
          - "$(CLUSTER_ID)"
          - "--kubelet-namespace"
          - "$(POD_NAMESPACE)"
          - "--kubelet-image"
          - {{ .Values.virtualKubelet.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          - "--init-kubelet-image"
          - {{ .Values.initVk.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: cluster-id
                key: cluster-id
          - name: POD_NAMESPACE
            valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 100m
            memory: 50M

