---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: foreign-unauth
rules:
  - apiGroups:
      - "discovery.liqo.io"
    resources:
      - federationrequests
    verbs:
      - get
      - create
      - delete

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unauth-user

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unauth-user
  namespace: default
subjects:
  - kind: ServiceAccount
    name: unauth-user
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: foreign-unauth
