// Copyright 2019-2026 The Liqo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	offloadingv1beta1 "github.com/liqotech/liqo/apis/offloading/v1beta1"
	applyconfigurationoffloadingv1beta1 "github.com/liqotech/liqo/pkg/client/applyconfiguration/offloading/v1beta1"
	scheme "github.com/liqotech/liqo/pkg/client/clientset/versioned/scheme"
)

// VirtualNodesGetter has a method to return a VirtualNodeInterface.
// A group's client should implement this interface.
type VirtualNodesGetter interface {
	VirtualNodes(namespace string) VirtualNodeInterface
}

// VirtualNodeInterface has methods to work with VirtualNode resources.
type VirtualNodeInterface interface {
	Create(ctx context.Context, virtualNode *offloadingv1beta1.VirtualNode, opts v1.CreateOptions) (*offloadingv1beta1.VirtualNode, error)
	Update(ctx context.Context, virtualNode *offloadingv1beta1.VirtualNode, opts v1.UpdateOptions) (*offloadingv1beta1.VirtualNode, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualNode *offloadingv1beta1.VirtualNode, opts v1.UpdateOptions) (*offloadingv1beta1.VirtualNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*offloadingv1beta1.VirtualNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*offloadingv1beta1.VirtualNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *offloadingv1beta1.VirtualNode, err error)
	Apply(ctx context.Context, virtualNode *applyconfigurationoffloadingv1beta1.VirtualNodeApplyConfiguration, opts v1.ApplyOptions) (result *offloadingv1beta1.VirtualNode, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, virtualNode *applyconfigurationoffloadingv1beta1.VirtualNodeApplyConfiguration, opts v1.ApplyOptions) (result *offloadingv1beta1.VirtualNode, err error)
	VirtualNodeExpansion
}

// virtualNodes implements VirtualNodeInterface
type virtualNodes struct {
	*gentype.ClientWithListAndApply[*offloadingv1beta1.VirtualNode, *offloadingv1beta1.VirtualNodeList, *applyconfigurationoffloadingv1beta1.VirtualNodeApplyConfiguration]
}

// newVirtualNodes returns a VirtualNodes
func newVirtualNodes(c *OffloadingV1beta1Client, namespace string) *virtualNodes {
	return &virtualNodes{
		gentype.NewClientWithListAndApply[*offloadingv1beta1.VirtualNode, *offloadingv1beta1.VirtualNodeList, *applyconfigurationoffloadingv1beta1.VirtualNodeApplyConfiguration](
			"virtualnodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *offloadingv1beta1.VirtualNode { return &offloadingv1beta1.VirtualNode{} },
			func() *offloadingv1beta1.VirtualNodeList { return &offloadingv1beta1.VirtualNodeList{} },
		),
	}
}
