// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Advertiser) DeepCopyInto(out *Advertiser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Advertiser.
func (in *Advertiser) DeepCopy() *Advertiser {
	if in == nil {
		return nil
	}
	out := new(Advertiser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Advertiser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiserList) DeepCopyInto(out *AdvertiserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Advertiser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiserList.
func (in *AdvertiserList) DeepCopy() *AdvertiserList {
	if in == nil {
		return nil
	}
	out := new(AdvertiserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdvertiserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiserSpec) DeepCopyInto(out *AdvertiserSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]Resource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Availability.DeepCopyInto(&out.Availability)
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	in.Validity.DeepCopyInto(&out.Validity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiserSpec.
func (in *AdvertiserSpec) DeepCopy() *AdvertiserSpec {
	if in == nil {
		return nil
	}
	out := new(AdvertiserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvertiserStatus) DeepCopyInto(out *AdvertiserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvertiserStatus.
func (in *AdvertiserStatus) DeepCopy() *AdvertiserStatus {
	if in == nil {
		return nil
	}
	out := new(AdvertiserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreeResource) DeepCopyInto(out *FreeResource) {
	*out = *in
	out.Cpu = in.Cpu.DeepCopy()
	out.CpuPrice = in.CpuPrice.DeepCopy()
	out.Ram = in.Ram.DeepCopy()
	out.RamPrice = in.RamPrice.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreeResource.
func (in *FreeResource) DeepCopy() *FreeResource {
	if in == nil {
		return nil
	}
	out := new(FreeResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
	out.Price = in.Price.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}
