// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/ipam/ipam.proto

package ipam

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseResult) Reset() {
	*x = ResponseResult{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseResult) ProtoMessage() {}

func (x *ResponseResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseResult.ProtoReflect.Descriptor instead.
func (*ResponseResult) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{0}
}

type IPAcquireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAcquireRequest) Reset() {
	*x = IPAcquireRequest{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAcquireRequest) ProtoMessage() {}

func (x *IPAcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAcquireRequest.ProtoReflect.Descriptor instead.
func (*IPAcquireRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{1}
}

func (x *IPAcquireRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type IPAcquireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Result        *ResponseResult        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAcquireResponse) Reset() {
	*x = IPAcquireResponse{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAcquireResponse) ProtoMessage() {}

func (x *IPAcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAcquireResponse.ProtoReflect.Descriptor instead.
func (*IPAcquireResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{2}
}

func (x *IPAcquireResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPAcquireResponse) GetResult() *ResponseResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type IPReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPReleaseRequest) Reset() {
	*x = IPReleaseRequest{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPReleaseRequest) ProtoMessage() {}

func (x *IPReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPReleaseRequest.ProtoReflect.Descriptor instead.
func (*IPReleaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{3}
}

func (x *IPReleaseRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPReleaseRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type IPReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ResponseResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPReleaseResponse) Reset() {
	*x = IPReleaseResponse{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPReleaseResponse) ProtoMessage() {}

func (x *IPReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPReleaseResponse.ProtoReflect.Descriptor instead.
func (*IPReleaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{4}
}

func (x *IPReleaseResponse) GetResult() *ResponseResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type NetworkAcquireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Immutable     bool                   `protobuf:"varint,2,opt,name=immutable,proto3" json:"immutable,omitempty"`       // If true, the network cannot be remapped. It will be allocated if available, or an error will be returned.
	PreAllocated  uint32                 `protobuf:"varint,3,opt,name=preAllocated,proto3" json:"preAllocated,omitempty"` // The number of IPs to pre-allocate (reserve) in the CIDR, starting from the first IP of the CIDR.
	Exclusive     bool                   `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`       // If true, the network is acquired exclusively. No other entity can acquire or use this network range. Applies only if immutable=true.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAcquireRequest) Reset() {
	*x = NetworkAcquireRequest{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAcquireRequest) ProtoMessage() {}

func (x *NetworkAcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAcquireRequest.ProtoReflect.Descriptor instead.
func (*NetworkAcquireRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkAcquireRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkAcquireRequest) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *NetworkAcquireRequest) GetPreAllocated() uint32 {
	if x != nil {
		return x.PreAllocated
	}
	return 0
}

func (x *NetworkAcquireRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type NetworkAcquireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Result        *ResponseResult        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAcquireResponse) Reset() {
	*x = NetworkAcquireResponse{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAcquireResponse) ProtoMessage() {}

func (x *NetworkAcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAcquireResponse.ProtoReflect.Descriptor instead.
func (*NetworkAcquireResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkAcquireResponse) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkAcquireResponse) GetResult() *ResponseResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type NetworkReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkReleaseRequest) Reset() {
	*x = NetworkReleaseRequest{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkReleaseRequest) ProtoMessage() {}

func (x *NetworkReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkReleaseRequest.ProtoReflect.Descriptor instead.
func (*NetworkReleaseRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkReleaseRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type NetworkReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ResponseResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkReleaseResponse) Reset() {
	*x = NetworkReleaseResponse{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkReleaseResponse) ProtoMessage() {}

func (x *NetworkReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkReleaseResponse.ProtoReflect.Descriptor instead.
func (*NetworkReleaseResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkReleaseResponse) GetResult() *ResponseResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type NetworkAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAvailableRequest) Reset() {
	*x = NetworkAvailableRequest{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAvailableRequest) ProtoMessage() {}

func (x *NetworkAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAvailableRequest.ProtoReflect.Descriptor instead.
func (*NetworkAvailableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkAvailableRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type NetworkAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Result        *ResponseResult        `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAvailableResponse) Reset() {
	*x = NetworkAvailableResponse{}
	mi := &file_pkg_ipam_ipam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAvailableResponse) ProtoMessage() {}

func (x *NetworkAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipam_ipam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAvailableResponse.ProtoReflect.Descriptor instead.
func (*NetworkAvailableResponse) Descriptor() ([]byte, []int) {
	return file_pkg_ipam_ipam_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkAvailableResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *NetworkAvailableResponse) GetResult() *ResponseResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_pkg_ipam_ipam_proto protoreflect.FileDescriptor

const file_pkg_ipam_ipam_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/ipam/ipam.proto\"\x10\n" +
	"\x0eResponseResult\"&\n" +
	"\x10IPAcquireRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"L\n" +
	"\x11IPAcquireResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\x0f.ResponseResultR\x06result\"6\n" +
	"\x10IPReleaseRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\"<\n" +
	"\x11IPReleaseResponse\x12'\n" +
	"\x06result\x18\x01 \x01(\v2\x0f.ResponseResultR\x06result\"\x8b\x01\n" +
	"\x15NetworkAcquireRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x1c\n" +
	"\timmutable\x18\x02 \x01(\bR\timmutable\x12\"\n" +
	"\fpreAllocated\x18\x03 \x01(\rR\fpreAllocated\x12\x1c\n" +
	"\texclusive\x18\x04 \x01(\bR\texclusive\"U\n" +
	"\x16NetworkAcquireResponse\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\x0f.ResponseResultR\x06result\"+\n" +
	"\x15NetworkReleaseRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"A\n" +
	"\x16NetworkReleaseResponse\x12'\n" +
	"\x06result\x18\x01 \x01(\v2\x0f.ResponseResultR\x06result\"-\n" +
	"\x17NetworkAvailableRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"a\n" +
	"\x18NetworkAvailableResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12'\n" +
	"\x06result\x18\x02 \x01(\v2\x0f.ResponseResultR\x06result2\xbf\x02\n" +
	"\x04IPAM\x122\n" +
	"\tIPAcquire\x12\x11.IPAcquireRequest\x1a\x12.IPAcquireResponse\x122\n" +
	"\tIPRelease\x12\x11.IPReleaseRequest\x1a\x12.IPReleaseResponse\x12A\n" +
	"\x0eNetworkAcquire\x12\x16.NetworkAcquireRequest\x1a\x17.NetworkAcquireResponse\x12A\n" +
	"\x0eNetworkRelease\x12\x16.NetworkReleaseRequest\x1a\x17.NetworkReleaseResponse\x12I\n" +
	"\x12NetworkIsAvailable\x12\x18.NetworkAvailableRequest\x1a\x19.NetworkAvailableResponseB\bZ\x06./ipamb\x06proto3"

var (
	file_pkg_ipam_ipam_proto_rawDescOnce sync.Once
	file_pkg_ipam_ipam_proto_rawDescData []byte
)

func file_pkg_ipam_ipam_proto_rawDescGZIP() []byte {
	file_pkg_ipam_ipam_proto_rawDescOnce.Do(func() {
		file_pkg_ipam_ipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ipam_ipam_proto_rawDesc), len(file_pkg_ipam_ipam_proto_rawDesc)))
	})
	return file_pkg_ipam_ipam_proto_rawDescData
}

var file_pkg_ipam_ipam_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_ipam_ipam_proto_goTypes = []any{
	(*ResponseResult)(nil),           // 0: ResponseResult
	(*IPAcquireRequest)(nil),         // 1: IPAcquireRequest
	(*IPAcquireResponse)(nil),        // 2: IPAcquireResponse
	(*IPReleaseRequest)(nil),         // 3: IPReleaseRequest
	(*IPReleaseResponse)(nil),        // 4: IPReleaseResponse
	(*NetworkAcquireRequest)(nil),    // 5: NetworkAcquireRequest
	(*NetworkAcquireResponse)(nil),   // 6: NetworkAcquireResponse
	(*NetworkReleaseRequest)(nil),    // 7: NetworkReleaseRequest
	(*NetworkReleaseResponse)(nil),   // 8: NetworkReleaseResponse
	(*NetworkAvailableRequest)(nil),  // 9: NetworkAvailableRequest
	(*NetworkAvailableResponse)(nil), // 10: NetworkAvailableResponse
}
var file_pkg_ipam_ipam_proto_depIdxs = []int32{
	0,  // 0: IPAcquireResponse.result:type_name -> ResponseResult
	0,  // 1: IPReleaseResponse.result:type_name -> ResponseResult
	0,  // 2: NetworkAcquireResponse.result:type_name -> ResponseResult
	0,  // 3: NetworkReleaseResponse.result:type_name -> ResponseResult
	0,  // 4: NetworkAvailableResponse.result:type_name -> ResponseResult
	1,  // 5: IPAM.IPAcquire:input_type -> IPAcquireRequest
	3,  // 6: IPAM.IPRelease:input_type -> IPReleaseRequest
	5,  // 7: IPAM.NetworkAcquire:input_type -> NetworkAcquireRequest
	7,  // 8: IPAM.NetworkRelease:input_type -> NetworkReleaseRequest
	9,  // 9: IPAM.NetworkIsAvailable:input_type -> NetworkAvailableRequest
	2,  // 10: IPAM.IPAcquire:output_type -> IPAcquireResponse
	4,  // 11: IPAM.IPRelease:output_type -> IPReleaseResponse
	6,  // 12: IPAM.NetworkAcquire:output_type -> NetworkAcquireResponse
	8,  // 13: IPAM.NetworkRelease:output_type -> NetworkReleaseResponse
	10, // 14: IPAM.NetworkIsAvailable:output_type -> NetworkAvailableResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_ipam_ipam_proto_init() }
func file_pkg_ipam_ipam_proto_init() {
	if File_pkg_ipam_ipam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ipam_ipam_proto_rawDesc), len(file_pkg_ipam_ipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_ipam_ipam_proto_goTypes,
		DependencyIndexes: file_pkg_ipam_ipam_proto_depIdxs,
		MessageInfos:      file_pkg_ipam_ipam_proto_msgTypes,
	}.Build()
	File_pkg_ipam_ipam_proto = out.File
	file_pkg_ipam_ipam_proto_goTypes = nil
	file_pkg_ipam_ipam_proto_depIdxs = nil
}
