apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: peeringrequests.discovery.liqo.io
spec:
  group: discovery.liqo.io
  names:
    kind: PeeringRequest
    singular: peeringrequest
    plural: peeringrequests
    shortNames:
      - pr
      - peer-req
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterID:
              type: string
              description: Cluster ID
            namespace:
              type: string
              description: Namespace where Liqo is deployed
            kubeConfigRef:
              type: object
              description: KubeConfig file (with Advertisement creation role) secret reference
          required:
            - clusterID
        status:
          description: PeeringRequestStatus defines the observed state of PeeringRequest
          properties:
            advertisementStatus:
              type: string