# syntax=docker/dockerfile:1

# CHANGE: Switched from debian-based Go image to Ubuntu Base
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash