---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sn-operator
  labels:
    k8s-app: sn-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sn-operator
subjects:
  - kind: ServiceAccount
    name: sn-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: schedulingnode-operator
  name: schedulingnode-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: schedulingnode-operator
  strategy: {}
  template:
    metadata:
      labels:
        run: schedulingnode-operator
    spec:
      serviceAccountName: sn-operator
      containers:
      - image: {{ .Values.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: schedulingnode-operator
        command: ["/usr/bin/schedulingNodeOperator"]
        resources:
          limits:
            cpu: 10m
            memory: 30M
          requests:
            cpu: 10m
            memory: 30M

