apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  labels:
  name: liqo-pre-delete
  namespace: liqo
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      name: liqo-pre-delete
    spec:
      containers:
      - command:
        - /usr/bin/uninstaller
        image: liqo/uninstaller-ci:51fac000ba9acd79a8a821277bd23abbc32ed356
        imagePullPolicy: IfNotPresent
        name: pre-delete-job
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccount: liqo-discovery
      serviceAccountName: liqo-discovery
      terminationGracePeriodSeconds: 30
