# Default values for liqo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##### Needed
suffix: ""
version: "latest"
pullPolicy: "IfNotPresent"
apiServer:
  ip: ""
  port: ""
authServer:
  ip: ""
  port: ""

nameOverride: ""
fullnameOverride: ""

advertisement:
  name: "advertisement"
  module: "sharing-protocol"
  podAnnotations: {}
  podLabels: {}
  imageName: ""
  config:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 5
    outgoingConfig:
      resourceSharingPercentage: 30
      enableBroadcaster: true
    keepaliveThreshold: 3
    keepaliveRetryTime: 20

route:
  name: "route"
  module: "networking"
  podAnnotations: {}
  podLabels: {}
  imageName: ""

gateway:
  name: "gateway"
  module: "networking"
  podAnnotations: {}
  podLabels: {}
  imageName: ""
  service:
    type: "NodePort"
    annotations: {}

networkManager:
  name: "network-manager"
  module: "networking"
  podAnnotations: {}
  podLabels: {}
  imageName: ""
  config:
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.0.0.0/16"
    reservedSubnets: []

crdReplicator:
  name: "crd-replicator"
  module: "replicating"
  podAnnotations: {}
  podLabels: {}
  image:
    repository: "liqo/crd-replicator"
    pullPolicy: "IfNotPresent"
  config:
    resourcesToReplicate:
      - group: net.liqo.io
        version: v1alpha1
        resource: networkconfigs

discovery:
  name: "discovery"
  module: "discovery"
  podAnnotations: {}
  podLabels: {}
  config:
    clusterName: "test"
    autojoin: true
    autojoinUntrusted: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    service: _liqo_api._tcp
    ttl: 90


auth:
  name: "auth"
  module: "discovery"
  podAnnotations:
    testAnnotationKey: "testAnnotationValue"
  podLabels:
    testLabelKey: "testAnnotationValue"
  imageName: "liqo/auth-service"
  service:
    type: "NodePort"
    annotations:
      testAnnotationKey: "testAnnotationValue"
  ingress:
    annotations: {}
    enable: false
    host: ""
    class: ""
  config:
    allowEmptyToken: true

#configuration values for the adv subchart
advertisementOperator:
  advController:
    image:
      repository: "liqo/advertisement-operator"
      pullPolicy: "IfNotPresent"
  broadcaster:
    image:
      repository: "liqo/advertisement-broadcaster"
      pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the networkModule subchart
networkModule:
  routeOperator:
    image:
      repository: "liqo/liqonet"
      pullPolicy: "IfNotPresent"
  tunnelEndpointOperator:
    image:
      repository: "liqo/liqonet"
      pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the tunnelendpointCreator subchart
tunnelEndpointCreator:
  image:
    repository: "liqo/liqonet"
    pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the schedulingNode subchart
schedulingNodeOperator:
  image:
    repository: "liqo/scheduling-node-operator"
    pullPolicy: "IfNotPresent"
  enabled: true

#configuration values for the mutatingWebhook subchart
liqoWebhook:
  webhook:
    image:
      repository: "liqo/liqo-webhook"
      pullPolicy: "IfNotPresent"
  webhookConfiguration:
    image:
      repository: "liqo/webhook-configuration"
      pullPolicy: "IfNotPresent"
  webhookServiceName: "liqo-webhook"
  certSecretName: "liqo-webhook-cert"
  enabled: true

discoveryOperator:
  image:
    repository: "liqo/discovery"
    pullPolicy: "IfNotPresent"
  apiServerIp: ""
  apiServerPort: ""
  enabled: true

peeringRequestOperator:
  operator:
    image:
      repository: "liqo/peering-request-operator"
      pullPolicy: "IfNotPresent"
  enabled: true

authService:
  image:
    repository: "liqo/auth-service"
    pullPolicy: "IfNotPresent"
  enabled: true


advController:
  image:
    repository: "liqo/advertisement-operator"
    pullPolicy: "IfNotPresent"

broadcaster:
  image:
    repository: "liqo/advertisement-broadcaster"
    pullPolicy: "IfNotPresent"

virtualKubelet:
  image:
    repository: "liqo/virtual-kubelet"
    pullPolicy: "IfNotPresent"

initVk:
  image:
    repository: "liqo/init-vkubelet"
    pullPolicy: "IfNotPresent"
