# Default values for liqo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##### Needed

# -- images' tag
tag: ""
# -- pullPolicy for liqo pods
pullPolicy: "IfNotPresent"
apiServer:
  # -- remote API server IP address
  address: ""
  # -- remote API server port
  port: ""

# -- liqo name override
nameOverride: ""
# -- full liqo name override
fullnameOverride: ""

advertisement:
  pod:
    # -- advertisement pod annotations
    annotations: {}
    # -- advertisement pod labels
    labels: {}
  # -- advertisement image repository
  imageName: "liqo/advertisement-operator"
  # -- broadcaster image repository
  broadcasterImageName: "liqo/advertisement-broadcaster"
  config:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 5
    outgoingConfig:
      resourceSharingPercentage: 30
      enableBroadcaster: true
    keepaliveThreshold: 3
    keepaliveRetryTime: 20

route:
  pod:
    # -- route pod annotations
    annotations: {}
    # -- route pod labels
    labels: {}
  # -- route image repository
  imageName: "liqo/liqonet"

gateway:
  pod:
    # -- gateway pod annotations
    annotations: {}
    # -- gateway pod labels
    labels: {}
  # -- gateway image repository
  imageName: "liqo/liqonet"
  service:
    # -- If you plan to use liqo over the Internet consider to change this field to "LoadBalancer".
    # More generally, if your cluster nodes are not directly reachable by the cluster to whom you are peering then change it to "LoadBalancer"
    type: "NodePort"
    annotations: {}

networkManager:
  pod:
    # -- networkManager pod annotations
    annotations: {}
    # -- networkManager pod labels
    labels: {}
  # -- networkManager image repository
  imageName: "liqo/liqonet"
  config:
    # -- the subnet used by the cluster for the pods, in CIDR notation
    podCIDR: ""
    # -- the subnet used by the cluster for the services, in CIDR notation
    serviceCIDR: ""
    # -- Usually the IPs used for the pods in k8s clusters belong to private subnets.
    # In order to prevent IP conflicting between locally used private subnets in your infrastructure and private subnets belonging to remote clusters
    # you need tell liqo the subnets used in your cluster. E.g if your cluster nodes belong to the 192.168.2.0/24 subnet then
    # you should add that subnet to the reservedSubnets. PodCIDR and serviceCIDR used in the local cluster are automatically added to the reserved list.
    reservedSubnets: []
    # -- set this field to true if you are deploying liqo in GKE cluster
    GKEProvider: false

crdReplicator:
  pod:
    # -- crdReplicator pod annotations
    annotations: {}
    # -- crdReplicator pod labels
    labels: {}
  # -- crdReplicator image repository
  imageName: "liqo/crd-replicator"

discovery:
  pod:
    # -- discovery pod annotations
    annotations: {}
    # -- discovery pod labels
    labels: {}
  # -- discovery image repository
  imageName: "liqo/discovery"
  config:
    clusterName: ""
    autojoin: true
    autojoinUntrusted: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    service: _liqo_api._tcp
    ttl: 90

auth:
  pod:
    # -- auth pod annotations
    annotations: {}
    # -- auth pod labels
    labels: {}
  # -- auth image repository
  imageName: "liqo/auth-service"
  initContainer:
    # -- auth init container image repository
    imageName: nginx:1.19
  service:
    # -- auth service type
    type: "NodePort"
    # -- auth service annotations
    annotations: {}
  # -- enable TLS for the Authentication Service Pod
  tls: true
  ingress:
    # -- auth ingress annotations
    annotations: {}
    enable: false
    host: ""
    port: ""
    class: ""
  config:
    # -- enable the authentication with an empty token. NB: use it only for testing installations
    allowEmptyToken: false

webhook:
  pod:
    # -- webhook pod annotations
    annotations: {}
    # -- webhook pod labels
    labels: {}
  # -- webhook image repository
  imageName: "liqo/liqo-webhook"
  initContainer:
    # -- webhook init container image repository
    imageName: "liqo/webhook-configuration"
  service:
    # -- webhook service type
    type: "ClusterIP"
    # -- webhook service annotations
    annotations: {}
  mutatingWebhookConfiguration:
    # -- mutatingWebhookConfiguration annotations
    annotations: {}
    # -- mutatingWebhookConfiguration namespace selector
    namespaceSelector:
      liqo.io/enabled: "true"

peeringRequest:
  pod:
    # -- peering request pod annotations
    annotations: {}
    # -- peering request pod labels
    labels: {}
  # -- peeringRequest image repository
  imageName:  "liqo/peering-request-operator"

virtualKubelet:
  # -- virtual kubelet image repository
  imageName: "liqo/virtual-kubelet"
  initContainer:
    # -- virtual kubelet init container image repository
    imageName: "liqo/init-vkubelet"
