# Default values for liqo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##### Needed
tag: ""
pullPolicy: "IfNotPresent"
apiServer:
  ip: ""
  port: ""
authServer:
  ip: ""
  port: ""

nameOverride: ""
fullnameOverride: ""

advertisement:
  name: "advertisement"
  module: "sharing-protocol"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/advertisement-operator"
  broadcasterImageName: "liqo/advertisement-broadcaster"
  config:
    ingoingConfig:
      acceptPolicy: AutoAcceptMax
      maxAcceptableAdvertisement: 5
    outgoingConfig:
      resourceSharingPercentage: 30
      enableBroadcaster: true
    keepaliveThreshold: 3
    keepaliveRetryTime: 20

route:
  name: "route"
  module: "networking"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/liqonet"

gateway:
  name: "gateway"
  module: "networking"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/liqonet"
  service:
    type: "NodePort"
    annotations: {}

networkManager:
  name: "network-manager"
  module: "networking"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/liqonet"
  config:
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.0.0.0/16"
    reservedSubnets: []

crdReplicator:
  name: "crd-replicator"
  module: "replicating"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/crd-replicator"
  config:
    resourcesToReplicate:
      - group: net.liqo.io
        version: v1alpha1
        resource: networkconfigs

discovery:
  name: "discovery"
  module: "discovery"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/discovery"
  config:
    clusterName: "test"
    autojoin: true
    autojoinUntrusted: true
    domain: local.
    enableAdvertisement: true
    enableDiscovery: true
    name: MyLiqo
    port: 6443
    service: _liqo_api._tcp
    ttl: 90

auth:
  name: "auth"
  module: "discovery"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/auth-service"
  initContainer:
    name: "cert-creator"
    imageName: nginx:1.19
  service:
    type: "NodePort"
    annotations: {}
  ingress:
    annotations: {}
    enable: false
    host: ""
    class: ""
  config:
    allowEmptyToken: true

webhook:
  name: "webhook"
  module: "webhook"
  pod:
    annotations: {}
    labels: {}
  imageName: "liqo/liqo-webhook"
  initContainer:
    name: "webhook-configuration"
    imageName: "liqo/webhook-configuration"
  service:
    type: "ClusterIP"
    annotations:
      testAnnotationKey: "testAnnotationValue"
  mutatingWebhookConfiguration:
    annotations:
      testAnnotationKey: "testLabelValue"
    namespaceSelector:
      liqo.io/enabled: "true"

peeringRequest:
  name: "peering-request"
  module: "discovery"
  pod:
    annotations: {}
    labels: {}
  imageName:  "liqo/peering-request-operator"

virtualKubelet:
  imageName: "liqo/virtual-kubelet"
  initContainer:
    imageName: "liqo/init-vkubelet"
