// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: pkg/liqo-controller-manager/resource-request-controller/resource-monitors/resource-reader.proto

package resourcemonitors

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceReaderClient is the client API for ResourceReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceReaderClient interface {
	ReadResources(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	RemoveCluster(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ResourceReader_SubscribeClient, error)
}

type resourceReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceReaderClient(cc grpc.ClientConnInterface) ResourceReaderClient {
	return &resourceReaderClient{cc}
}

func (c *resourceReaderClient) ReadResources(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/resource_reader/ReadResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceReaderClient) RemoveCluster(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/resource_reader/RemoveCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceReaderClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ResourceReader_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ResourceReader_ServiceDesc.Streams[0], "/resource_reader/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceReaderSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourceReader_SubscribeClient interface {
	Recv() (*UpdateNotification, error)
	grpc.ClientStream
}

type resourceReaderSubscribeClient struct {
	grpc.ClientStream
}

func (x *resourceReaderSubscribeClient) Recv() (*UpdateNotification, error) {
	m := new(UpdateNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ResourceReaderServer is the server API for ResourceReader service.
// All implementations must embed UnimplementedResourceReaderServer
// for forward compatibility
type ResourceReaderServer interface {
	ReadResources(context.Context, *ReadRequest) (*ReadResponse, error)
	RemoveCluster(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Subscribe(*SubscribeRequest, ResourceReader_SubscribeServer) error
	mustEmbedUnimplementedResourceReaderServer()
}

// UnimplementedResourceReaderServer must be embedded to have forward compatible implementations.
type UnimplementedResourceReaderServer struct {
}

func (UnimplementedResourceReaderServer) ReadResources(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadResources not implemented")
}
func (UnimplementedResourceReaderServer) RemoveCluster(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCluster not implemented")
}
func (UnimplementedResourceReaderServer) Subscribe(*SubscribeRequest, ResourceReader_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedResourceReaderServer) mustEmbedUnimplementedResourceReaderServer() {}

// UnsafeResourceReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceReaderServer will
// result in compilation errors.
type UnsafeResourceReaderServer interface {
	mustEmbedUnimplementedResourceReaderServer()
}

func RegisterResourceReaderServer(s grpc.ServiceRegistrar, srv ResourceReaderServer) {
	s.RegisterService(&ResourceReader_ServiceDesc, srv)
}

func _ResourceReader_ReadResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceReaderServer).ReadResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_reader/ReadResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceReaderServer).ReadResources(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceReader_RemoveCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceReaderServer).RemoveCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource_reader/RemoveCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceReaderServer).RemoveCluster(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceReader_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceReaderServer).Subscribe(m, &resourceReaderSubscribeServer{stream})
}

type ResourceReader_SubscribeServer interface {
	Send(*UpdateNotification) error
	grpc.ServerStream
}

type resourceReaderSubscribeServer struct {
	grpc.ServerStream
}

func (x *resourceReaderSubscribeServer) Send(m *UpdateNotification) error {
	return x.ServerStream.SendMsg(m)
}

// ResourceReader_ServiceDesc is the grpc.ServiceDesc for ResourceReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resource_reader",
	HandlerType: (*ResourceReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadResources",
			Handler:    _ResourceReader_ReadResources_Handler,
		},
		{
			MethodName: "RemoveCluster",
			Handler:    _ResourceReader_RemoveCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ResourceReader_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/liqo-controller-manager/resource-request-controller/resource-monitors/resource-reader.proto",
}
