---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-sa
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: discovery
    app: liqo.io
subjects:
  - kind: ServiceAccount
    name: discovery-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: discovery
    app: liqo.io
  name: discovery
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: discovery
  template:
    metadata:
      labels:
        run: discovery
    spec:
      serviceAccountName: discovery-sa
      containers:
        - image: {{ .Values.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          name: discovery
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/entrypoint.sh", "/usr/bin/discovery"]
          args:
          - "--namespace"
          - "$(POD_NAMESPACE)"
          - "--requeueAfter"
          - "30"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{ if .Values.apiServerIp }}
            - name: APISERVER
              value: {{ .Values.apiServerIp }}
            {{ end }}
            {{ if .Values.apiServerPort }}
            - name: APISERVER_PORT
              value: {{ .Values.apiServerPort }}
            {{ end }}
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates
              name: ca-certificates
      volumes:
        - name: ca-certificates
          configMap:
            name: trusted-ca-certificates
      hostNetwork: true
