apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: liqo.io
data:
  name: MyLiqo                      # service name
  service: _liqo._tcp               # service type
  domain: local.                    # service domain
  port: '6443'                      # service port

  waitTime: '2'                     # wait response time
  updateTime: '3'                   # time between queries

  enableDiscovery: 'true'           # enable service discovery
  enableAdvertisement: 'true'       # enable service advertisement

  autoJoin: 'true'                  # enable automatic join process
