// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeployment) DeepCopyInto(out *DroneFederatedDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeployment.
func (in *DroneFederatedDeployment) DeepCopy() *DroneFederatedDeployment {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DroneFederatedDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeploymentList) DeepCopyInto(out *DroneFederatedDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DroneFederatedDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeploymentList.
func (in *DroneFederatedDeploymentList) DeepCopy() *DroneFederatedDeploymentList {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DroneFederatedDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeploymentOverrides) DeepCopyInto(out *DroneFederatedDeploymentOverrides) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeploymentOverrides.
func (in *DroneFederatedDeploymentOverrides) DeepCopy() *DroneFederatedDeploymentOverrides {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeploymentOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeploymentPlacement) DeepCopyInto(out *DroneFederatedDeploymentPlacement) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]DroneFederatedDeploymentPlacementClusters, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeploymentPlacement.
func (in *DroneFederatedDeploymentPlacement) DeepCopy() *DroneFederatedDeploymentPlacement {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeploymentPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeploymentPlacementClusters) DeepCopyInto(out *DroneFederatedDeploymentPlacementClusters) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeploymentPlacementClusters.
func (in *DroneFederatedDeploymentPlacementClusters) DeepCopy() *DroneFederatedDeploymentPlacementClusters {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeploymentPlacementClusters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeploymentSpec) DeepCopyInto(out *DroneFederatedDeploymentSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	in.Placement.DeepCopyInto(&out.Placement)
	out.Overrides = in.Overrides
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeploymentSpec.
func (in *DroneFederatedDeploymentSpec) DeepCopy() *DroneFederatedDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DroneFederatedDeploymentStatus) DeepCopyInto(out *DroneFederatedDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DroneFederatedDeploymentStatus.
func (in *DroneFederatedDeploymentStatus) DeepCopy() *DroneFederatedDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DroneFederatedDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
