name: "Installer Testing"
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
jobs:
  installer-testing:
    name: "Installer Testing"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test the installer
        run: |
          BATS="${{ github.workspace }}/test/installer/libs/bats/bin/bats"
          TEST="${{ github.workspace }}/test/installer/install-test.sh"
          "${BATS}" "${TEST}"
