name: Check Website Helm documentation
on:
  release:
    types:
      - created
      - edited
jobs:
  generated-helm-documentation:
    name: Check Generated Helm Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          persist-credentials: false

      - name: Gather the website docs differences
        id: docs-diff
        run: |
          sed '1 { /^---/ { :a N; /\n---\n/! ba; d} }' docs/pages/installation/chart_values.md > deployments/liqo/docs_README.md
          output=$(diff deployments/liqo/README.md deployments/liqo/docs_README.md | head -n 100)
          exit_code=$([ "${output}" ] && echo 1 || echo 0)

          # Required to correctly manage multi-line outputs
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"

          # Store the different as step output
          echo "::set-output name=diff::${output}"

          # Trigger a failure in case the diff is not empty
          exit ${exit_code}

      - name: Log the error if the diff is not empty (in case the comment cannot be generated)
        run: |
          echo "The website documentations of Helm appears to be out-of-date."
          echo
          echo "Here it is an excerpt of the diff:"
          echo "${{ steps.docs-diff.outputs.diff }}"
        if: failure()

      - name: Issue a comment in case the diff is not empty
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The website documentations of Helm appears to be out-of-date.

            Please, replace the documentation in `docs/pages/User/Install/chart_values.md` with the one in `/deployments/liqo/README.md`
            while mantaining the Hugo header as follows:
            ```
            ---
            title: Helm values
            weight: x
            ---

            ...
            ```

            <details>
              <summary>Here it is an excerpt of the diff:</summary>

              ```diff
              ${{ steps.docs-diff.outputs.diff }}
              ```
            </details>
          reactions: confused
        if: |
          github.event_name != 'push' && failure() &&
          github.event.pull_request.head.repo.full_name == github.repository
