name: Build the documentation website 
on:
  repository_dispatch:
    types:
      - doc-build-command
  push:
    tags:
      - 'v*'
    branches:
      - master   

jobs:
  configure:
    name: Preliminary configuration
    runs-on: ubuntu-latest
    outputs:
      commit-ref: ${{ steps.configure.outputs.commit-ref }}
      master: ${{ steps.configure.outputs.master }}
      repo-name: ${{ steps.configure.outputs.repo-name }}
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      if: startsWith(github.ref, 'refs/tags/v')
    - name: Configure
      id: configure
      run: |
        # The ref of the commit to checkout (do not use the merge commit if repository dispatch)
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          echo "::set-output name=master::false"
          echo "::set-output name=commit-ref::${{ github.event.client_payload.pull_request.head.sha }}"
        elif [ "${{ steps.get_version.outputs.VERSION }}" != "" ]; then
          echo "::set-output name=master::false"
          echo "::set-output name=commit-ref::${{ steps.get_version.outputs.VERSION }}"
        else
          echo "::set-output name=master::true"
          echo "::set-output name=commit-ref::${{ github.sha }}"
        fi

        if [ "${{ github.event_name }}" != "repository_dispatch" ]; then
           echo "::set-output name=repo-name::${{ github.repository }}"
        else
           echo "::set-output name=repo-name::${{ github.event.client_payload.github.payload.repository.full_name }}"
        fi

  docs-pipeline-trigger:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: "${{ needs.configure.outputs.commit-ref }}"
          repository: "${{ needs.configure.outputs.repo-name }}"
          persist-credentials: false
      - name: Notify Event to doc-website
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: liqotech/doc-website
          event-type: "dev-event"
          client-payload: |
            {
              "master": "${{ needs.configure.outputs.master }}",
              "commit": "${{ needs.configure.outputs.commit-ref }}",
              "repo-name": "${{ needs.configure.outputs.repo-name }}"
            }