name: Go
on: [push]
jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
        - virtual-kubelet
        - liqonet
        - advertisement-broadcaster
        - advertisement-operator
        - init-vkubelet
        - schedulingnode-operator
        - discovery
        - peering-request-operator
        - tray-agent
        - secret-creation
        - init-pod-mutator
        - pod-mutator
        - peering-request-webhook-init
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Push ${{ matrix.component }} image on repo
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liqo/${{ matrix.component }}
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: build/${{ matrix.component }}/Dockerfile
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ github.sha }}"
        if: github.ref == 'refs/heads/master'
      - name: Push ${{ matrix.component }} image on repo
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liqo/${{ matrix.component }}-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          dockerfile: build/${{ matrix.component }}/Dockerfile
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ github.sha }}"
        if: github.ref != 'refs/heads/master'
   release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() && github.ref == 'refs/heads/master' # Pick up events even if the job fails or is canceled.
   test:
    name: Test Launch
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -u github.com/ory/go-acc
    - name: install tray-agent dependencies
      run: sudo apt-get install gcc libgtk-3-dev libappindicator3-dev libwebkit2gtk-4.0-dev
    - run: go-acc ./...
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: Integration Test # default: 8398a7@action-slack
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() && github.ref == 'refs/heads/master' # Pick up events even if the job fails or is canceled.
