name: Integration Pipeline
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  configure:
    name: Preliminary configuration
    runs-on: ubuntu-latest
    outputs:
      commit_ref: ${{ steps.configure.outputs.commit_ref }}
      repo-suffix: ${{ steps.configure.outputs.repo-suffix }}
      ok-to-continue: ${{ steps.configure.outputs.ok-to-continue }}
      master: ${{ steps.configure.outputs.master }}
      repo-name: ${{ steps.configure.outputs.repo-name }}
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      if: startsWith(github.ref, 'refs/tags/v')
    - name: Configure
      id: configure
      run: |
        # The ref of the commit to checkout (do not use the merge commit if pull request)
        if [ "${{ github.event_name }}" == "pull_request_target" ]; then
          echo "::set-output name=master::false"
          echo "::set-output name=commit_ref::${{ github.event.pull_request.head.sha }}"
        elif [ "${{ steps.get_version.outputs.VERSION }}" != "" ]; then
          echo "::set-output name=master::false"
          echo "::set-output name=commit_ref::${{ steps.get_version.outputs.VERSION }}"
        else
          echo "::set-output name=master::true"
          echo "::set-output name=commit_ref::${{ github.sha }}"
        fi

        # The suffix to append to the repository name if not triggered by a push to master
        [[ "${{ steps.get_version.outputs.VERSION }}" == "" ]] && \
          echo "::set-output name=repo-suffix::-ci" ||
          echo "::set-output name=repo-suffix::"

        if [ "${{ github.event_name }}" != "pull_request_target" ]; then
           echo "::set-output name=ok-to-continue::true"
           echo "::set-output name=repo-name::${{ github.repository }}"
        elif [ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]; then
           echo "::set-output name=ok-to-continue::true"
           echo "::set-output name=repo-name::${{ github.repository }}"
        elif [ "${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}" == "true" ]; then
           echo "::set-output name=ok-to-continue::true"
           echo "::set-output name=repo-name::${{ github.event.pull_request.head.repo.full_name }}"
        else
           echo "::set-output name=ok-to-continue::false"
           echo "::set-output name=repo-name::${{ github.event.pull_request.head.repo.full_name }}"
        fi

  build:
    runs-on: ubuntu-latest
    needs: configure
    if: needs.configure.outputs.ok-to-continue == 'true'
    strategy:
      fail-fast: false
      matrix:
        component:
        - virtual-kubelet
        - liqonet
        - advertisement-broadcaster
        - advertisement-operator
        - init-vkubelet
        - scheduling-node-operator
        - discovery
        - peering-request-operator
        - liqo-webhook
        - crd-replicator
        - auth-service
        - webhook-configuration
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: "${{ needs.configure.outputs.commit_ref }}"
          repository: "${{ needs.configure.outputs.repo-name }}"
          persist-credentials: false


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (and Publish) ${{ matrix.component }} image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            liqo/${{ matrix.component }}${{ needs.configure.outputs.repo-suffix }}:latest
            liqo/${{ matrix.component }}${{ needs.configure.outputs.repo-suffix }}:${{ needs.configure.outputs.commit_ref }}
          push: true
          file: build/${{ matrix.component }}/Dockerfile

  e2e-test-trigger:
     runs-on: ubuntu-latest
     needs: [build, configure]
     if: needs.configure.outputs.ok-to-continue == 'true' && github.event.pull_request.draft == false
     strategy:
       fail-fast: false
       matrix:
         component:
         - liqops
         - doc-website
     steps:
       - uses: actions/checkout@v2
         with:
           ref: "${{ env.commit_ref }}"
       - name: Notify Event to ${{ matrix.component }}
         uses: peter-evans/repository-dispatch@v1
         with:
           token: ${{ secrets.CI_TOKEN }}
           repository: liqotech/${{ matrix.component }}
           event-type: "dev-event"
           client-payload: |
             {
               "master": "${{ needs.configure.outputs.master }}",
               "commit": "${{ needs.configure.outputs.commit_ref }}",
               "repo-name": "${{ needs.configure.outputs.repo-name }}"
             }
  release:
    runs-on: ubuntu-latest
    needs: [build, test, configure]
    if: github.event_name == 'push' && github.event.repository.full_name == 'liqotech/liqo' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # The changelog generation requires the entire history
          fetch-depth: 0
          ref: "${{ needs.configure.outputs.commit_ref }}"
          repository: "${{ needs.configure.outputs.repo-name }}"
          persist-credentials: false

      - name: Get the Liqo version to be released
        id: version
        run: echo "version::${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get the latest Liqo release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: last-release
        with:
          repository: ${{ github.repository }}

      - name: Generate the CHANGELOG
        uses: RiskLedger/generate-changelog@v1.2
        id: changelog
        with:
          from: ${{ steps.last-release.outputs.release }}
          to: ${{ needs.configure.outputs.commit_ref }}
        env:
          GITHUB_AUTH: ${{ secrets.CI_TOKEN }}

      - name: Save the CHANGELOG as a file
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > ./CHANGELOG.md
          sed -i "1s/.*/## Changes since ${{ needs.configure.outputs.commit_ref }}/" ./CHANGELOG.md

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.configure.outputs.commit_ref }}
          release_name: ${{ needs.configure.outputs.commit_ref }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

  test:
    name: Launch Test
    runs-on: ubuntu-20.04
    needs: configure
    if: needs.configure.outputs.ok-to-continue == 'true' && github.event.pull_request.draft == false
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: "${{ needs.configure.outputs.commit_ref }}"
        repository: "${{ needs.configure.outputs.repo-name }}"
        persist-credentials: false

    - name: Install Kubebuilder
      run: |
        version=2.3.1 # latest stable version
        arch=amd64
        curl -L -O "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_${arch}.tar.gz"
        tar -zxvf kubebuilder_${version}_linux_${arch}.tar.gz
        mv kubebuilder_${version}_linux_${arch} kubebuilder && sudo mv kubebuilder /usr/local/

    - name: Get dependencies for Test execution
      run: |
        go get -u github.com/ory/go-acc

    - name: Launch Test
      run: go-acc ./... --ignore liqo/test/e2e

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt

  wait-approve:
    name: Wait for the ok-to-test label to test pr on fork
    runs-on: ubuntu-20.04
    needs: configure
    if: needs.configure.outputs.ok-to-continue == 'false'
    steps:
      - name: Issue the greeting comment
        uses: peter-evans/create-or-update-comment@v1
        with:
            token: ${{ secrets.CI_TOKEN }}
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              Hi @${{ github.event.pull_request.user.login }}. Thanks for your PR!

              I'm waiting for a Liqo member to verify that this patch is reasonable to test. If it is, they should reply with /ok-to-test.

              Once the patch is verified, the new status will be reflected by the ok-to-test label.