name: Linting
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: goLint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          only-new-issues: true
          version: v1.34.0
          args: --timeout=600s
  shelllint:
    name: shellLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
