name: Merge the current PR
on:
  repository_dispatch:
    types:
      - merge-command

jobs:
  automerge:
    name: Merge
    runs-on: ubuntu-latest

    steps:
      - name: Add the merge-requested label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.CI_TOKEN }}"
          number: ${{ github.event.client_payload.github.payload.issue.number }}
          labels: merge-requested

      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.CI_TOKEN }}"
          MERGE_LABELS: "merge-requested,!hold"
          MERGE_METHOD: "rebase"
          MERGE_RETRY_SLEEP: "30000"  # 30 seconds
          # Use a fake UPDATE_LABEL, to prevent rebase from being triggered
          # https://github.com/pascalgn/automerge-action/issues/86
          UPDATE_LABELS: "never-perform-rebase,!hold"
          UPDATE_METHOD: "rebase"

      - name: Remove the merge-requested label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: "${{ secrets.CI_TOKEN }}"
          number: ${{ github.event.client_payload.github.payload.issue.number }}
          labels: merge-requested
